### PR TITLE
Nerfs the tommygun and makes it R&D only.

### PR DESCRIPTION
**Pull request by Iamgoofball**

### CODE REVIEW

**Comment by drynwyn** [comment]
There is no good reason a force 15 non-stun gun should require more materials an more research then a laser cannon or submachine gun when those two are vastly and obviously superior. Hell, a simple laser gun is better than a tommy gun.

**Comment by Iamgoofball** [comment]
k

**Comment by drynwyn** [comment]
I don't think it needs much of a nerf at all. 15 force ranged weapon that
requires ammo, not charging, is plenty weak for a "ghetto" weapon.

**Comment by Atskadan** [comment]
honestly it should just be like the normal SMG: you print off the gun for kind of cheap, and it's in a lockbox. the ammo is what's expensive.
the snowflake "DIY tommygun" doesn't really add anything but convolution to an already unnecessary weapon.
additionally it probably shouldnt require actual traitor gear to build; the smg doesn't, and it's better. this only has an edge in ammo count, and i think that's a good thing. it's a sidegrade, or perhaps, a sidearm - in conjunction with a stun weapon, 750 damage per mag is useful.

**Comment by ghost** [comment]
WHY NOT MAKE A 30 ROUND STRAIGHT MAG FOR IT, YOU KNOW, THE KIND THOMPSONS NORMALLY USE, THEN IT'D BE MORE BALANCED

**Comment by Atskadan** [comment]
because there is a difference between a thompson and a tommygun
thompson refers to the old one that soldiers used, like how you call old people by their real names
tommygun is the one with the foregrip and the drum mags that mobsters used

**Comment by ghost** [comment]
no uh that's not how gun naming works, not all gangsters used those winding drum mags, but they were still called tommyguns because it's more fun to say than thompson, stop watching hollywood movies and learn your shit because the two names are virtually interchangeable

**Comment by ghost** [comment]
What I suggest is completely reverting this tommy gun building shit honestly there's no reason for it to be a thing at all when the tommy gun is just a larger gimmicky uzi for admin events and gangster mobs. I like the idea of gun building but yeah when it requires a nerf this drastic there's no reason for it to exist at all.

Bump it back up to c20r stats (aka m1911), remove the stupid snowflake projectile code, and keep it as it is but remove the building and protolathe thing. A glock works fucking fine for gang weapons if you REALLY want to make a gang with guns and they're extremely easy to make. I'd rather this gun not exist right now as there's no reason for it to when we have perfectly balanced weapons in the protolathe already.

Hell, change the tommy gun building to glock building. The worst that could happen is assistants could build a 20 brute projectile weapon with no stun. You could even keep the glock barrel in the hacked autolathe, it wouldn't cause NEARLY as many problems as the 50 round fucking tommy gun does.

Plus, glocks are WAY more modern gangster than the tommy gun, with dannos' new bandana stuff.

**Comment by Atskadan** [comment]
if you call a Real Old People thompson a tommygun you have no respect

**Comment by Iamgoofball** [comment]
> remove the stupid snowflake projectile code

so adding a new bullet type is snowflake now?

**Comment by ghost** [comment]
Adding a new bullet type only used by the tommy gun and literally naming it 'tommy' is yes. there's a reason the other ones aren't named '9mm' or '45' or 'c20r'.

**Comment by Iamgoofball** [comment]
no other bullets had the attributes I wanted for the tommygun

it's not like this new bullet causes immense game lag

**Comment by ghost** [comment]
It's sloppy because other guns might use it down the road, you never know.

**Comment by Atskadan** [comment]
then just change the name.
adding new bullet types is easy and not really a snowflake thing. unlike snowflake code, bullet types are automatically able to be used by other guns down the road due to the way they are coded.
if we ever want guns that shoot bullets for 15 damage and no stun, then we have a round for that now. 
the name of a bullet or snippet of code isn't what makes it snowflake; it's whether or not it can be used for other things, and whether it is necessary to have that new snippet of code for the item to work, or if there is already an existing proc for it, etc.

**Comment by ghost** [comment]
if someone down the line wanted to change the name for the tommy gun bullet he'd also have to change the name in the bullet casings (caliber) file so he'd have to fix something that another coder could have easily done in the first place when he originally made the bullet. it might not be snowflake but it's awfully inconsiderate of other people down the line who might contribute to guns to make a bullet type specifically for your gun, pellet is the only example of this i can see right now but pellet has an actual name change for shotgun buckshot.

Also like I said I like the ghetto gun smithing idea but it should really be for the glock so security doesn't have to deal with that tommy gun shit and gangs/revs can be more gangster as fuck with dem austrian guns.

**Comment by Iamgoofball** [comment]
> he'd also have to change the name in the bullet casings (caliber) file

this takes like 5 seconds

if you can't be bothered to do 5 seconds of work to change the name of something, you need to put more effort in

**Comment by Atskadan** [comment]
the name of a bullet which isn't even represented in game is not an important thing 
it's literally only used in the code

**Comment by ghost** [comment]
It's still inconsiderate~

Anyway like I said stop doing this, the tommy gun is FINE as a fucking .45 gun because that's what it is, making it a nerfed snowflake .45 just so you can put it in the protolathe is a fucking stupid, stupid idea.

Change the construction process to a glock, un-nerf the tommy gun, remove the tommy gun from the protolathe/construction and keep it to 1940s gangster gimmick mobs, add plasteel to the glock build process (the grip is plastic, might as well build that out of plasteel, 2-3 sheets should be plenty balanced)

Also make the switchblade handle 2-3 plasteel sheets too

**Comment by Iamgoofball** [comment]
un-needed PR, paprika did a different nerf

**Pull request closed without merging**
