### PR TITLE
Spreading Stun Shells and Riot Shotguns

### PR DESCRIPTION
**Pull request by JStheguy**
-Adds a new shotgun shell that fires stunning pellets.  (Read:  The horrific offspring of a Buckshot shell and a taser)
-Adds a riot shotgun that starts with the new shells and replaces the current riot shotguns in the armory.
-The new shell type can be made in the protolathe.
-Riot shotguns can be ordered from cargo.

### CODE REVIEW

**Comment by Atskadan** [comment]
doesnt use map merge tool

**Comment by JStheguy** [comment]
I tried to use it and i didn't work.
For some reason even after I did everything according to the wiki guide it still says there are ~10000 changed tiles.

**Comment by ghost** [comment]
Why not replace beanbag with a spreading beanbag to make it less shit, this is basically a direct upgrade from stun shells rather than a sidegrade

Plus the bartender would appreciate it if beanbags spread instead

**Comment by Atskadan** [comment]
the map merger does work
if you cant get it to work, ask someone in irc

**Comment by Atskadan** [comment]
also yeah i agree this is kind of OP
>shoot shotgun down a hallway
>everyone in the hallway is stunned

**Comment by Psyentific** [comment]
Problem - If you don't have spread or power, non-lethal shotguns are inferior to tasers/e-guns due to ammo capacity and pump action.
Currently, Beanbag rounds and stun shells are negligably different - Beanbags are 10 brute and stun, while stunshells are 5 brute and a longer stun. This means that riot shotguns and combat shotguns are shittier tasers, so there's no reason to use them.

You need to differentiate non-lethal shotguns from tasers, and this does a pretty good job of that. If I was coding this, I'd keep the stun buckshot as-is, but I'd also make beanbag rounds scatter and deal stam damage per pellet.

**Comment by ghost** [comment]
Keep in mind shotgun pellets bypass energy shields and dual eswords. That's a big, big thing.

**Comment by JStheguy** [comment]
Holy shit it finally worked
yes

**Comment by ghost** [comment]
Remove the stock from the spriiiiiite it would look so much cooler and tacticool with that pistol grip

tacticool

Edit: I updated the sprite to be even more tacticool and angry looking.

**Comment by Atskadan** [comment]
that looks so bad

**Comment by ghost** [comment]
As opposed to..? It's just an edit of the sprite JS added and you don't have to be so upset about the saber thing miggles.

**Comment by Psyentific** [comment]
I want muh stock back. Wood furniture. >:[

**Comment by Iamgoofball** [comment]
we have that screen shake shit rigged up with variables and shit, right?

make the screen shake lower if you have a stock on it, and make it so you can attach a stock to the weapon.

this way we can have the no stock version and one with a stock

**Comment by ghost** [comment]
The isn't a resprite of the normal shotgun, the wood shotgun still exists. This is an entirely new shotgun, with a capacity in between normal and combat, that comes loaded with spreading beanbag shots that sec can use for riots more effectively than normal beanbags.

I figured, since sec would be using it with a riot shield a lot of the time, that it would make sense to be stockless and in a compact package.

**Pull request closed without merging**
