### PR TITLE
[EMERGENCY] Fixes undershirts so that they do not look like they are made of cardboard boxes.

### PR DESCRIPTION
**Pull request by MrSnapwalk**
SO BOXY, OH GOD. (Couldn't do anything about the shirts I took from Bay, though. They'll just look boxy, I guess.)

### CODE REVIEW

**Comment by RemieRichards** [comment]
> Couldn't do anything about the shirts I took from Bay

Right click the side images in that little 4 direction view, export as Png, Fix it, Stick it back in.

**Comment by MrSnapwalk** [comment]
What I mean is that I literally can't make any modifications that make it look better. If I remove the offending pixel, it looks absolutely crap due to the skin showing up underneath.

**Comment by RemieRichards** [comment]
but it does the same with your Tank tops too, does it not?
I tested the pixel removal on your Sec one and a pixel does show through.

**Comment by MrSnapwalk** [comment]
Yes, but with tank tops it actually makes sense and does not look like crap (as opposed to the boxes we accidentally have now).

**Comment by RemieRichards** [comment]
oh fuck, Sorry my head's still a mess since my news, you said "Shirts" didn't you? Sorry, I got confused.

**Pull request merged**
