### PR TITLE
Updates changelog header

### PR DESCRIPTION
**Pull request by ghost**
#792

Here is a hosted version for easy viewing: http://puu.sh/a7Vvo/ecd916c9cc.html

In addition to updating the links so they point to NTStation resources instead of /tg/station's, with Atskadan's approval I've changed the credits to list coders by contributions, so those who have committed the most get credited first.
e.g.
**NT contributors:** paprika, phil235, Iamgoofball, danno, Atskadan, GunHog, RemieRichards, Steelpoint, Donkie, VistaPOWA, Kelenius, Menshin, MrStonedOne, Jordie0608, Firecage, JStheguy, Limeliz, AnturK, StarToad, Nerolat, drynwyn, Petershmitz, Niknakflak, RandomMarine, Nnelg, Alek2ander, Nienhaus2, Boggart, Deantwo, Dorsisdwarf, Tomeno, Walter0o, YotaXP, CollenN, PinkyGatchabee, Neerti

(ordered by contributions to NTstation since it was forked from /tg/)

**/tg/ contributors:** Giacom, Ikarrus, Aranclanos, Petethegoat, Razharas, Cheridan, Incoming5643, Miauw62, Malkevin, MrPerson, hornygranny, Carn, Ergovisavi, dannno, ChuckTheSheep, Metacide, fleure, Tenebrosity, SuperSayu, Perakp, KazeEspada, AlexanderUlanH, errorage, Rolan7, kyrahabattoir, JJRcop, dumpdavidson, caelaislinn, Mloc, Tastyfish

(ordered by contributions to NTstation since the /tg/station GitHub project was created)

To explain the methodology, I split the lists so the /tg/station contributors didn't overshadow the NT ones due to the relatively short amount of time NTstation has been around to contribute to. The lists are different from one another to save space (i.e. people who have contributed to both repos are credited on the one they've contributed the highest proportion of commits to). If anyone thinks they are wrongly categorised, they can request to be moved to the other list, but this means being lower on the other list.

If you aren't listed and think you should be, please tell me.

### CODE REVIEW

**Comment by ghost** [comment]
Simply too based, thank you tenebrosity

**Comment by Atskadan** [comment]
i think the ordered contributors list would be great, please do that

**Comment by RemieRichards** [comment]
> i think the ordered contributors list would be great, please do that

**Comment by Neerti** [comment]
Yours truly isn't on there.
Also I think there was drama on /tg/codebase about someone getting cut from the list, so careful about that.

**Comment by ike709** [comment]
I made 2 PRs, put me at the beginning of the list. :P

**Comment by ghost** [comment]
I'd list everyone so it didn't seem like a competition but then I think I'd get in trouble due to the length. It'd be like 100 v. the current 60.

**Comment by ghost** [comment]
Ah yes the real reason I have submitted so much to NT was to be at the front of a list of names. Finally it all comes together.

**Comment by Neerti** [comment]
Can I be moved to NT section?

**Comment by ghost** [comment]
> Ah yes the real reason I have submitted so much to NT was to be at the front of a list of names. Finally it all comes together.

Now people will have an idea of who has put the most work into what they're playing.

**Comment by ghost** [comment]
I know it's a little odd, but could you put a 2 after my name? Like how it is for the Spriters section? I'm normally logged into Byond under Nienhaus2.
If not it's okay, doesn't matter to much.

**Comment by ghost** [comment]
Yeah, I don't mind.

**Comment by ghost** [comment]
Ah, thanks mate.

**Comment by ghost** [comment]
Thanks.

**Pull request merged**
