### PR TITLE
Replaces the GravGen alarm with a louder, more distressing sound.

### PR DESCRIPTION
**Pull request by ghost**
Sample: https://dl.dropboxusercontent.com/u/831776/alert.ogg

Poll: http://www.ss13.eu/phpbb/viewtopic.php?f=48&t=4415

### CODE REVIEW

**Comment by Atskadan** [comment]
i liked signal.ogg
it sounds like a slower fire alarm and its not as earbleed
plus alarm.ogg is already used for when your air tank is low, signal.ogg is really iconic for the grav gen

**Comment by ghost** [comment]
It's played at half speed. It sounds nothing like the air tank version.

**Comment by ghost** [comment]
Here's a sample of how it actually sounds in game.

https://dl.dropboxusercontent.com/u/831776/alert.ogg

**Comment by Atskadan** [comment]
i still think i like signal.ogg better

**Comment by Neerti** [comment]
I like ikky's version.

**Comment by ghost** [comment]
So the poll was closed in favor of approval...

**Pull request merged**
