### PR TITLE
Detective Work (trace evidence) [Ready]

### PR DESCRIPTION
**Pull request by Petethegoat**
Added gun trace evidence.
Adds evidence on the shooter, the victim (including hit objects), the gun, and the casings.
Adds appropriate descriptions for most projectiles. Laser guns don't leave traces on the shooter.

Doubled and then some the chance for fibers to be placed on objects and clothing.

Adds fibers from the victim to weapons.

Unrelated fixes to make eguns and coins show up in the map editor.

### CODE REVIEW

**Comment by Petethegoat** [comment]
Oh, this also slightly adjusts the sabre sprite, (R&D SMG) to make the foregrip less fat. Nothing major.

**Comment by Petethegoat** [comment]
It is supposed to be two underscores, yes.

**Comment by CollenN** [comment]
I like this change.

Perhaps something that might be neat would be ballistic markings on bullet casings and guns, allowing detectives to match bullet casings with the gun that made them?

**Comment by Petethegoat** [comment]
That's definitely something I've thought about, although I'm not sure how much use it'd get (how often are there going to be multiple possible guns for you to compare with?)
But I'll keep it in mind.

**Comment by Atskadan** [comment]
Inspecting bullets already tells you what caliber they're in, and you can easily narrow down the list with that. Outside of summon guns there's only a few guns that fire bullets. I think scanning a person who has been shot or the clothes of someone who has been shot should show a bullet hole of a certain size for each caliber.

**Comment by Petethegoat** [comment]
I'm happy with this. Merge at will.

**Comment by Atskadan** [comment]
We can’t automatically merge this pull request.

**Comment by Petethegoat** [comment]
Fixed.

**Pull request merged**
