### PR TITLE
Latex gloves nerf [Ready]

### PR DESCRIPTION
**Pull request by Petethegoat**
Latex gloves no longer prevent fingerprints from being transferred to items. Updates the desc of gloves and their box.
Adds a generic proc to put custom detective fibres on atoms. (unused)

Removed black gloves from cargo and mining lockers.
Adds fingerless gloves, and adds them to cargo tech closets.
Tidies up washing_machine.dm and makes items without an item_color not wash.

### CODE REVIEW

**Comment by ghost** [comment]
I'll give this like 2 days for people to look at it. If no one says anything then I'll merge it.

**Comment by Petethegoat** [comment]
I'm making a thread now. No rush.

**Comment by Petethegoat** [comment]
FYI the Travis build didn't failed because of the PR. This compiles fine.
Some dependency website for Travis is down, I think.

**Comment by Atskadan** [comment]
r i p latex 
you were my fetish ;_;

**Comment by Limeliz** [comment]
Where's the logic in latex gloves doing finger prints?

**Comment by Atskadan** [comment]
Because latex gloves are thin and can leave prints IRL. Also because gameplay reasons.
If there's a box of gloves in a public area that gives you a pretty decent chance of not leaving evidence, then the detective has a harder time identifying criminals.

**Pull request merged**
