### PR TITLE
Void Dwellers

### PR DESCRIPTION
**Pull request by Thunder12345**
First PR. Void Dwellers are a new mob, intended to spawn rarely in deep
space. I don't know how to do this, but the basic mob is now coded. They
have 40 health, do 10 brute damage per hit, and can move freely in
space. They leave no corpse or loot. I leave the actual spawning to
someone with the knowledge to do so properly.

### CODE REVIEW

**Comment by ghost** [comment]
Picture?

**Comment by Thunder12345** [comment]
http://i.imgur.com/tW5MHxx.png

**Comment by AnturK** [comment]
Not sure if we need to make space even more dangerous than it is but make them stun and drag people to nearest space tile and i'm sold.

**Comment by Atskadan** [comment]
With upcoming space content, some areas of space will be roguelike-difficult. More mobs to help that happen is nice.

**Comment by Atskadan** [comment]
..I don't see a reason against it either..?

**Comment by Neerti** [comment]
More stuff for mapmakers to play with isn't bad.

**Pull request merged**
