### PR TITLE
Save/Load

### PR DESCRIPTION
**Pull request by ACCount12**
You are a badmin, delaying the round, spawning a ton of items with custom names, armor vars, icons and contents for an event. And then some random bombgriefer ruins everything! And you need to restart a server, delay the round again and then spawn ton of items with custom names, icons, contents... 

Not anymore! With our brand new ShitSpawner 9000 you can spawn custom clothing, items, even mobs on your local server, save them, then load save files everywhere!
1. Set up local server.
2. Spawn!
3. Debug -> Debug Verbs
4. Click on item and select Save To File. (you can use lockers to save a ton of items at once)
5. Connect to server you want to fill with your ~~shi~~ spawn.
6. Debug  -> Load Save File
7. RMB on target turf -> Spawn Save File Contents

Save files can store everything you can spawn, including custom icons and custom onmob icons from my last badminpowers update.

Known troubles:
- Save To File is in Debug Verbs for a reason. It can crash server if you are trying to save item that has a ton of external referrences. Making external ref vars /tmp/ works, but i fixed only vars for mobs and items.
- Saving humans and items is totally safe, saving structures can be dangerous, saving atmos, telecomm and powernet machines will crash the server.
- Saving too many items at once triggers server's infinite loop check.
- Sideloaded icon referrenced multiple times loads incorrectly. BYOND's bug i think, see http://www.byond.com/forum/?post=1663894

### CODE REVIEW

**Comment by RemieRichards** [comment]
- Changing permanent vars into temp ones may have unseen consequences
- The Admin messages state that the admin is actively trying to crash the server, this is misleading.
- The Risk of crashes is sooo damn high, I can't accept this in such an unstable state

**Comment by Iamgoofball** [comment]
Admins already have stuff at their disposal that can crash the server quicker then this.

We should run it by SoS though.

**Comment by ACCount12** [comment]
> Changing permanent vars into temp ones may have unseen consequences

BYOND docs:

> The tmp type modifier indicates that an object variable should not be automatically written to the save file. This could mean that the variable is transient--that is, it is calculated at run-time and need not be saved. It could also indicated that the designer will handle saving of that variable specially and wishes to bypass the automated routine. 

/tmp/ is used in savefiles S/L only.

**Comment by RemieRichards** [comment]
Ah, Fair enough.

**Comment by ACCount12** [comment]
> The Admin messages state that the admin is actively trying to crash the server, this is misleading.

This is to ensure nobody ever will use Save To File on live server. There is a message "Are you sure you want to save [A]? THIS IS UNSAFE AND CAN CRASH THE SERVER! USE ON LOCAL SERVER ONLY!" when saving.

> The Risk of crashes is sooo damn high, I can't accept this in such an unstable state

Loading is safe. Saving is unsafe but saving must be used on local server only. 

+DEBUG has SDQL2 button (in same Debug Verbs), it can crash server easily. A lot of Mapping Debug Verbs can freeze the game for ~5mins and fuck up the graphics. VV panel has Mass Mod Var and Mass Delete, it can crash the server or ruin the round completely.

**Comment by ACCount12** [comment]
Also you can try to crash the test server by saving various items/mobs. If server will crash, report this to me. I fixed most common servercrashers like radios and pulls.

**Comment by ACCount12** [comment]
Fixed two known troubles, fixed some possible crashes. Ready to merge i think.

**Comment by Iamgoofball** [comment]
this still ready to merge?

**Pull request closed without merging**
