### PR TITLE
Adds Chemical Seed Splicing

### PR DESCRIPTION
**Pull request by Iamgoofball**
http://i.imgur.com/LU6SIFq.png?1
This pull request adds the Seed Splicer.

You can use a reagent container on the Seed Splicer to scan the master reagent inside the reagent container to the buffer on the splicer. If something is already saved to the buffer it will overwrite it with the new data.
If you then use a Seed Packet on the splicer it will splice together the chemical and the seed's DNA, allowing that plant to grow that chemical.

That plant will then grow the chemical you splice in, allowing botany to become more useful to the chemists and the chef.

### CODE REVIEW

**Comment by Atskadan** [comment]
It sounds kinda OP that you can splice in any chemical. Is there any sort of work you have to do to get it, any resource that you have to use, or what? Is it just free chems for all? Would people be making unstable mutagen tomatoes every round?

**Comment by vista-** [comment]
Inb4 nitro & adminordrazine plants

**Comment by Intigracy** [comment]
You can't get adminordrazine by any means other than adminspawn.

Sans href fuckery, which mostly is fixed. At least everything people know about.

**Comment by Atskadan** [comment]
Poll ended in no/indecision. 8 yes 11 no.

**Comment by Iamgoofball** [comment]
i put up a poll for this? wow this was awhile ago

**Pull request closed without merging**
