### PR TITLE
Initial work on z-level defines. [Don't Merge]

### PR DESCRIPTION
**Pull request by Petethegoat**
Adds #defines for z-levels, which can be overridden by maps.
Allows maps to override the accessible z-levels list (which z-levels you can find in space, and the chance of going to them).

Unfinished and largely untested. Don't merge.

### CODE REVIEW

**Comment by Petethegoat** [comment]
Testing Travis, don't mind me.

**Comment by RemieRichards** [comment]
This should make working with Z-levels easier without having to remember which is station and which is Centcom etc. Even though it's unfinished, :+1: Good work pete.

**Comment by Petethegoat** [comment]
More Travis testing

**Comment by Iamgoofball** [comment]
Travis says it won't compile but travis is also not telling me what the hell it's doing.

**Comment by Petethegoat** [comment]
Still working on Travis. This shouldn't be merged anyway.

**Comment by Petethegoat** [comment]
I will probably make this PR at /tg/ instead, and then bring it here next time we merge. Closing for now.

**Pull request closed without merging**
