### PR TITLE
Removes Every Colon operator from Gamemode code. ALL OF THEM.

### PR DESCRIPTION
**Pull request by RemieRichards**
- I have Removed every instance of Colon Operators in the Game mode code.
- I have added gamemode_helpers.dm containing "game_is_EXAMPLE_mode(var/ticker_mode)" procs
- I have removed _some_ ancient commented out code, it will never return so, Bye bye for good.

Bow before me code peasants. Nah but seriously guys don't use colons.

<b>For a Reviewer:</b>
For whomever wishes to review this, Considering the importance of the code that was changed here, I was extremely careful to maintain the original functionality of it all, but with nicer code (And no DAMN COLONS) so you'll need to trust me, or get a second opinion from another Coder.

### CODE REVIEW

**Comment by Atskadan** [comment]
has this been tested?

**Comment by RemieRichards** [comment]
No, Besides Compile test and Travis's Compile test. All it does is swap the checks out for nicer ones and cleans up colons using typecasting (something that I've done loads of, and that is used all over the codebase) I understand where you're coming from though, It's freaking Gamemode code afterall

(not to mention, it's hard to test gamemodes with one person)

**Comment by Atskadan** [comment]
alright
if youre sure that it's ready, ill merge it when i get home

**Comment by RemieRichards** [comment]
Good, (I've read through the local and github versions of the code, and I'm changing mob Antag statuses and I'm seeing no issues, but again, if there isn't anything (there shouldn't be) it will only appear in live testing)

**Pull request merged**
