### PR TITLE
Removes the genetics powers virus symptom. [Don't Merge]

### PR DESCRIPTION
**Pull request by Petethegoat**
Removes the genetics powers virus symptom.
The disability one remains, for now.
Plus a bonus typo fix.

Wait for more feedback in http://www.ss13.eu/phpbb/viewtopic.php?f=42&t=4075 before merging.

### CODE REVIEW

**Comment by GunHog** [comment]
As I said on the thread, I do not support this one. Removing hulk is a more acceptable nerf in my opinion.

**Comment by Petethegoat** [comment]
I'll probably change the implementation, depending on the feedback. This almost certainly isn't the final PR.

**Comment by KazeEspada** [comment]
Although I haven played in a while, wouldn't it be better to make it even harder to get? or even just removing it from the possibility of appearing without admin help.  I don't like the idea of removing content from virology.

**Comment by Petethegoat** [comment]
Given that the thread has died I think I'll close this for now.

**Pull request closed without merging**
