### PR TITLE
Scroll through hair styles and facial hair

### PR DESCRIPTION
**Pull request by Limeliz**
Adds < and > buttons to character setup screen to easily scroll to next
or previous hair style and facial hair, intead of opening the popup with
a long unsorted list.

Also adds two procs for returning the value of the previous or next index in a list.

### CODE REVIEW

**Comment by ghost** [comment]
I want a gif pretty please.

**Comment by RemieRichards** [comment]
gif us a gif pls. :)

**Comment by Limeliz** [comment]
Preview gif as requested

**Comment by RemieRichards** [comment]
Literally the best. :+1:

**Comment by Limeliz** [comment]
Yaaaay! :+1:

**Pull request merged**
