### PR TITLE
Fixes assistant registration and adds assistant alt titles

### PR DESCRIPTION
**Pull request by ghost**
Scanning an assistant's ID card with your own will give them an alt title depending on your job now in addition to basic access. An example would be a medical doctor scanning an ID card and the assistant having the job title of 'nurse'.

I'm not especially creative so if people have suggestions they can leave them below.

### CODE REVIEW

**Comment by ghost** [comment]
Oh my god whyyyy neerti whyyyyy

**Comment by ghost** [comment]
> invisible commit
> nothing changed
> changes 20 files

i sure do love git

**Comment by krypt-n** [comment]
~~It is a merge commit. You can see the changes when you click on the second parent.~~
Me being stupid

**Comment by ghost** [comment]
That's not the point, it totally screwed my PR.

**Comment by krypt-n** [comment]
Oh, I see it now. Github was refreshing very slowly. No idea what happened there.

**Pull request closed without merging**
