### PR TITLE
Added a friendly note to the Map Files folder regarding Metastation.

### PR DESCRIPTION
**Pull request by Iamgoofball**
Added a very nice and friendly note to the Map Files folder regarding Metastation.

### CODE REVIEW

**Comment by PolymorphBlue** [comment]
I think that's a bit aggressive, but an actual friendly note would be fine if Metacide preferred to be the only one to edit it.

**Comment by Iamgoofball** [comment]
Yeah, over at Tgstation we had an issue where people or maintainers would merge changes to metastation fucking shit up for when he actually tried to do a metastation PR, so it's always been better to let him update it.

**Comment by PolymorphBlue** [comment]
Well, it's not necessarily intuitive (we can edit the /tg/ station map), but I understand that it's better if only Metacide does it.   So could you please change the note to be nicer?  Just something saying don't edit the metacide map, please, because it breaks git automerging for the map the next time metacide himself wants to change it.  Please forward change requests to the map to him.

**Comment by Iamgoofball** [comment]
Yeah, trying to get git to let me commit the making it nicer now, give it a few seconds.

**Comment by Intigracy** [comment]
This pull request was retarded.

If you use the map merger tool you can edit the map just fine and it won't affect him unless he's editing one of the tiles you are. Leaving it unedited when you added/changed something is the reason tg's codebase causes metastation to be uncompilable frequently.

**Pull request merged**
