### PR TITLE
Stolen Bugfixes

### PR DESCRIPTION
**Pull request by ike709**
Assuming this should all even be one PR. (Waiting for probable "Closed" because of it.)

Steals some bugfixes/tweaks from /tg/. Note: I am a newb at BYOND coding so yeah.
All the credit goes to whoever created the original PRs linked below (Still not sure why I left links to the original /tg/ PRs.)

Aranclanos's service borg violin fix: https://github.com/tgstation/-tg-station/pull/4030

Changed supply status display from SUPPLY to CARGO so the icon doesn't clip as much. Credit to Ikarrus. https://github.com/tgstation/-tg-station/pull/3933/files

Lockboxes can now be unlocked by a PDA with ID inside. Credit to LandoTheClimber. https://github.com/tgstation/-tg-station/pull/3978 (If you can think of other things that should be unlockable with a PDA, let me know)

Fixes the gravity generator not updating your gravity status. Credit to Giacom :heart:
https://github.com/tgstation/-tg-station/pull/3920

Fixes dead people floating in space randomly. Credit to Kelenius.
https://github.com/tgstation/-tg-station/pull/3980

Fixes spamming ready button toggling it. :heart: Credit to A-t48
https://github.com/tgstation/-tg-station/pull/4200

### CODE REVIEW

**Comment by ike709** [comment]
Should be ready for merging unless anyone knows of other bugfixes I can steal. I tested pretty much everything... Insert yelling/closing for multiple bugfixes in one PR below.

**Comment by ghost** [comment]
Are we not doing a mass merge of ALL /tg/ bugfixes/optimizations anymore? That seems more efficient if someone is willing to do it. I'm willing to test and root out bugs with conflicts, too.

**Comment by ghost** [comment]
https://github.com/tgstation/-tg-station/pull/4090

Port this too. It's a fix of a big introduced by /tg/#3980 which causes you to not be able to float diagonally when you throw shit diagonally.

**Comment by ike709** [comment]
@paprka http://gyazo.com/199d121622ed8de4a9aff0e58479f93a

**Comment by ike709** [comment]
I really don't feel like doing a mass merge at 2:30AM. if you want to go ahead. Port their new strip menu while you are at it.

**Comment by ghost** [comment]
Well these are the most pressing bugs that need to be addressed immediately anyway. I personally appreciate it.

**Comment by ike709** [comment]
I just looked for the bugs that pissed me off the most and stole the bugfixes :smile: Glad I pleased the almighty paprka.

**Comment by ghost** [comment]
I've lost too many corpses to that corpse drifting bug.

**Comment by Atskadan** [comment]
now that tg is on another feature freeze we're going to do another merge
this time more carefully

**Comment by ike709** [comment]
I'm pretty sure all of these were before the feature freeze.

**Comment by ghost** [comment]
Well it means we can halt our features to pull their bugfixes as well. This PR might not be necessary if we do that.

**Comment by Atskadan** [comment]
i'll get working on the next merge soon. this time i'll put up a thread for everyone to discuss which things should or shouldnt be in and hopefully attract some people to do some more review.
it won't be necessary because the merge will contain all those fixes and more, as well as new features.
so for now im going to close this.

**Comment by ike709** [comment]
Could this be reopened since there hasn't been a mass merge yet and these bugs are really annoying?

**Comment by ike709** [comment]
Eh... What... I'm... Gonna just close and reopen a new PR for this later.

**Comment by ike709** [comment]
rip

**Pull request closed without merging**
