### PR TITLE
Dedust an ancient dark ritual : A*

### PR DESCRIPTION
**Pull request by Menshin**
As per request, here's  the NT port of the /tg A\* dedusting.

See https://github.com/tgstation/-tg-station/pull/4138 .

### CODE REVIEW

**Comment by RemieRichards** [comment]
Fantastic! Is this ready for merge?

**Comment by Menshin** [comment]
It has been heavily tested on my (/tg) test server and lightly on NT (followed Beepsky and sent MULEbot to security and back) with success.

Should be ready to merge then.

No feedback from /tg for now, we can wait a little for it if you wish.

**Comment by ghost** [comment]
de_dust

**Comment by Menshin** [comment]
So, someone noticed after all...

**Comment by RemieRichards** [comment]
I'll wait a day for /tg/ to nitpick the hell out of everything ;)

**Comment by RemieRichards** [comment]
/tg/ merged.

**Pull request merged**
