### PR TITLE
Ports /tg/'s AI HUD!

### PR DESCRIPTION
**Pull request by GunHog**
Shameless ripoff of https://github.com/tgstation/-tg-station/pull/4048
Credit to Kelenius for the code.

Details found in his PR link.
New sprites by MrSnapwalk!
screenshot 2014-07-12 00 10 21

Also added myself to admins.txt.

In order from left to right: Return to core, camera list, track with camera, camera lights, crew monitor, crew manifest, alerts, vox, emergency shuttle, state laws, PDA send, PDA recieve, take image, view images, sensor mode.

### CODE REVIEW

**Comment by ike709** [comment]
Well this is going to take some getting used to.

**Comment by GunHog** [comment]
I am certain you will enjoy it! :)  This will be merge-able once I acquire better sprites!

**Comment by ghost** [comment]
It's awesome as fuck.

**Comment by GunHog** [comment]
Should be ready now!

**Comment by RemieRichards** [comment]
Sprites are a bit blue/orange. are they Hudstyle specific? ala Plasmafire and Midnight?

**Comment by GunHog** [comment]
No, there is only one style.

**Comment by RemieRichards** [comment]
Ewww. Completely wrong for Midnight then, the only one it matches is Plasmafire.
This disappoints me as I play exclusively with Midnight.

**Comment by MrSnapwalk** [comment]
@RemieRichards, they weren't meant to match with either Plasmafire or Midnight. If you'd like me to spend a few more days creating two alternate sets for each style, I could do that.

**Comment by ChangelingRain** [comment]
See the comments on the /tg/ station pull for what they should look like.

**Comment by RemieRichards** [comment]
@MrSnapwalk It's a HUD, there are very few special case HUDs that ignore the styles we have, so if possible, please do, Gia and MP seem to share this opinion also.

**Comment by GunHog** [comment]
@MrSnapwalk just post them here or ping me in IRC with beepsky, and I will add them. If you decide to make sets that match the client UI style, let me know so I can figure out how that works and update accordingly.

**Comment by MrSnapwalk** [comment]
Did a quick recolor, making the orange into green. Thoughts?
http://puu.sh/abzeb/f2ff5be412.png
EDIT: Got a request for a lighter blue.
http://puu.sh/abBlf/828f850cb0.png
EDIT 2: Here's the .dmi for the blue and green ones.
http://puu.sh/abPDp/40f1bdab8b.dmi

**Comment by GunHog** [comment]
Let me know which set you guys want, and I will set it!

**Comment by GunHog** [comment]
...conflicts? With what? Oh god why

**Pull request merged**
