### PR TITLE
Changes to welder. Makes it look manlier.

### PR DESCRIPTION
**Pull request by Pewtershmitz**
Check for yourself.

http://i.imgur.com/nxH5kXS.png

Signed-off-by: Pewtershmitz xengan@gmail.com

### CODE REVIEW

**Comment by Iamgoofball** [comment]
Mann/10

**Comment by Atskadan** [comment]
why rainbow

**Comment by Pewtershmitz** [comment]
Well, It's a gauge.

**Comment by ACCount12** [comment]
-1/10

**Comment by ghost** [comment]
flamethrower tank

**Pull request closed without merging**
