### PR TITLE
Latest /tg/ merge, Box shuttle fix [Ready]

### PR DESCRIPTION
**Pull request by Petethegoat**
Reverts our map changes, I will replace these shortly.

### CODE REVIEW

**Comment by RemieRichards** [comment]
:+1:

**Comment by Atskadan** [comment]
Should be easy to just copy over the kitchen and use the merge tool. Do that first.

**Comment by Atskadan** [comment]
u didnt use the merg tul
also is the tg one the same as what's live now or the one you showed me in irc

**Comment by Petethegoat** [comment]
It's yours with the pipe/wire fixes.

**Comment by Atskadan** [comment]
Mine HAD the pipe/wire fixes and you DIDIDN'T PASTETHEH TMEMEMEMTMESMTMMEM
ok ill merge it

**Comment by Petethegoat** [comment]
ill cut u

**Pull request merged**
