### PR TITLE
Adds treaded syndie borg sprite

### PR DESCRIPTION
**Pull request by ghost**
Named 'treadhound' in the file

Credit to Mechoid
wov6zoa

This is for an upcoming ~thing~ that will be pr'd later but might as well have them in now for admin sprite swaps if people wanna be tankborg

### CODE REVIEW

**Comment by GunHog** [comment]
[Acheron-7SYN Intensifies]

**Comment by Atskadan** [comment]
ok

**Comment by Iamgoofball** [comment]
jesus miggles a triplepost

**Comment by GunHog** [comment]
Why have you not merged it yet? I do not think anyone would have issue with Mechoid getting his sprites in.

**Comment by Atskadan** [comment]
because macs

**Pull request merged**
