### PR TITLE
Mining and Labour shuttles will not move if the nuke disk is on board

### PR DESCRIPTION
**Pull request by ghost**
Additionally,
-Adds labour shuttle to admin secrets
-Admin shuttle moves have no delay and ignore the disk check

### CODE REVIEW

**Comment by ghost** [comment]
Add in-use AI cores to this please.

**Comment by Atskadan** [comment]
^

**Comment by ghost** [comment]
Why?

**Comment by Atskadan** [comment]
So you don't have AI's on the mining station

**Comment by ghost** [comment]
I'll save it for another PR, as there are still plenty of other ways AIs can travel to the mining station.

**Comment by Atskadan** [comment]
Fair enough.

**Pull request merged**
