### PR TITLE
You can now walk/run on adjacent tables

### PR DESCRIPTION
**Pull request by ike709**
Top priority pls merge asap most important feature ever in spessman history.
https://github.com/tgstation/-tg-station/pull/4282 Steals this, so now when Niknak builds a strip club he doesn't have to keep teleporting the stripper around. Credit to paprka for the tg code and Zuhayr for the original Bay code.

### CODE REVIEW

**Comment by ghost** [comment]
Credit to zuphyer or whatever from bay for the code, he did it, not me.

**Comment by ike709** [comment]
Then credit to that guy

**Comment by RemieRichards** [comment]
Are there any unprotected tables (as in, just tables used as baricades, no windoors etc) on the map?
because I smell people building tables on themselves so they can abuse this.

**Comment by ike709** [comment]
The only one is the medbay reception desk thing, which is just chairs and a crew monitoring computer. People can just get other people to put them on tables anyways...

**Pull request merged**
