### PR TITLE
Kitchen Modification 3: RETURN OF DEEP FRIED EVERYTHING

### PR DESCRIPTION
**Pull request by Iamgoofball**
So I got the results back on that Deep Fried Everything user poll.
http://www.ss13.eu/tgdb/nt/ingamepolls.php

66 voted for keeping Deep fried everything, 40 for not keeping it, and 11 abstained.

As such, I'm bringing it back.

You cannot deep fry, cerealize, or candyize the nuke disk, rest easy nuke ops.

You can also take apart sandwiches and such by clicking on it in hand, allowing you to save the contents of the sandwich.

### CODE REVIEW

**Comment by ghost** [comment]
Dumb, enjoy all the tears

**Comment by Iamgoofball** [comment]
so r u

;-)

**Comment by ghost** [comment]
Also that poll has nothing to do with everything sandwiches or cerealized everything or candyizing everything, congrats on the rigging

**Comment by Iamgoofball** [comment]
I talked with miggles, and he said I didn't need to do another poll for the other machines

the everything sandwiches is required for the oven and shit to work with it

**Comment by Atskadan** [comment]
i said you wouldnt need a poll for the cereal maker

**Comment by Iamgoofball** [comment]
p. much all the cooking machines work the same, and I said "cereal maker and anything like that", so I figured you approved the other ones too, but alright

**Comment by ghost** [comment]
crunching random items up into tiny bits to make it into cereal or deep frying random items to make them edible is funny but you should really add some more critical items to the 'do not eat' list like the blueprints, CE magboots, medals, etc.

Alternatively, keep 'fying everything' but make frying identical to grilling in that non-edible items are still usable as items, and you can't eat them, but they're still deep fried so the chef can wear deep fried clothes and shit. You could include the nuke disk in this too.

**Comment by Atskadan** [comment]
paprika has good ideas you should do that

**Comment by Iamgoofball** [comment]
I can do the blacklist.

**Comment by GunHog** [comment]
Actually Pap's idea is quite an optimal compromise. You cannot abuse the deep fryer or such this way, as it would be a purely cosmetic and tasty change.

**Comment by Atskadan** [comment]
goobal pls

**Comment by Iamgoofball** [comment]
alright

**Comment by GunHog** [comment]
Really consider just making deep-frying cosmetic and not a super easy way to essentially delete important or powerful items.

**Comment by Iamgoofball** [comment]
spacing's easier then this to destroy items you know

i don't need to hack a door, have someone throw me over the counter, or steal an ID to space something

**Comment by Atskadan** [comment]
except you have never seen anyone space things in large quantities
when deep frying everything was a thing, people deep fried absolutely everything they could get their hands on <i>every round</i>

**Comment by Iamgoofball** [comment]
alright, then, i'll do it

**Comment by Atskadan** [comment]
cant be merged
edit: also you didnt do it

**Comment by Iamgoofball** [comment]
been busy

will do in the future

**Pull request closed without merging**
