### PR TITLE
Nerfs Hostile Lockdown.

### PR DESCRIPTION
**Pull request by GunHog**
Poll thread here: http://tgstation13.org/phpBB/viewtopic.php?f=16&t=731

This power's original intent was to slow down the crew such that the AI had time to respond to mounting threats against it.

It would seem that it is _too_ effective in this regard, and when paired with plasma, would wipe out nearly the entire crew in mere minutes.

I bear full responsibility for any rounds ruined though this feature.

<B>EDITED AGAIN - Tue, Jul 8:</B>
- <b> Airlocks are no longer shocked.</b>
- Cost doubled to 40 CPU time.
- Bolted airlocks will have their bolt light status unchanged (The
  lights will be on unless turned off beforehand)
- Opening/Closing code optimized to reduce lag potential.
- Fire doors are now closed without activating the alarm, making them
  much less annoying.
- Short cooldown introduced for performance reasons.

### CODE REVIEW

**Comment by Iamgoofball** [comment]
eh

make it only lock down for 1-2 minutes and not be reusable

that should help

**Comment by ghost** [comment]
Why not remove the ability to shunt with this like the borger machine and make it more expensive or something

**Comment by Iamgoofball** [comment]
hm, 30 seconds then, disables shunt, more expensive then

**Comment by Tokiko1** [comment]
How about giving the crew a 10-20 second warning before the lockdown happens? Not enough to go get all supplies to fight the AI, but enough to not have the majority of the crew locked up in a random room with no chance of escape.

**Comment by ghost** [comment]
The shocking part is the part I dislike the most, honestly; anyone can hack a door with a few tools and especially engineers, but yellow gloves are kind of rare and it makes it a real pain and more than just a quick 'speedbump', it can shut down a large majority of players out of the round. Just remove the shock part and I'm sure the ability would be less easy mode considering AIs would still have to manually shock doors and all that.

**Comment by Lumipharon** [comment]
Being trapped with no way out sucks, especially when the one responsible wasn't even targetting you/know where you are.
Not THAT many crewmembers have the tools to bypass shocked doors (removing walls etc), and even fewer have insulated gloves.
So Yeah, I would say that shocking the doors is an awful part of it.

**Comment by GunHog** [comment]
If it is agreeable with the community, the following changes I would make are:
- Bolt lights not being turned off, providing warning to average+ players that they may be shocked.
- Conversion of the disable proc to automatically activate after two minutes.
- Making it one use only - the AI will have to be decisive about when to deploy it.
- Increase the cost to 40 CPU.

All of these except it being one use only was my original design spec, before it was suggested that it would be underpowered and unused. If it turns out that people just want it gone totally, feel free to merge this PR as is.

**Comment by ghost** [comment]
The people who said it would be underpowered were 'AI iz bad!' apologists and I personally don't take their thoughts on balance seriously as they don't know how to interprit AI malf winrates :-1: 

Yeah okay a 60+ player round on sybil can absolutely shit on AIs and yeah this power is totally necessary and a good idea to curb the tide of people rushing the core but coupled with plasma it's absolutely devastating because not everyone knows how to get out of a room with shocked grilles, and being trapped in maint with it is even worse.

**Comment by Atskadan** [comment]
> on sybil

do you know what server we're on

gun hog, please make a new thread with all of your changes outlined so we can get a more accurate poll

**Comment by ghost** [comment]
he added it to sybil as well and didn't make any changes for the same thing here which he should have because like i said sybil is different

**Comment by Atskadan** [comment]
then he can make those changes there, and here if the community wants it

**Comment by GunHog** [comment]
Poll thread linked in OP.

**Comment by RemieRichards** [comment]
As of present the option in the poll with the most votes is No Nerf/Removal. 
However the combined votes that can all be considered "Change" of some kind are greater.

How are to we proceed? The "Team" with the most votes or the individual option with the most?

**Comment by GunHog** [comment]
I am open to suggestions or compromise. The poll result is unexpected - I had figured it would be a close call between "nerf" and "remove". Usednapkin's poll had strong support, but I am seeing the opposite here. A different, weaker nerf perhaps? @paprka would likely provide good input for proceeding.

**Comment by ghost** [comment]
just remove it entirely gun hog omfg ur ideas suck

no but i didn't expect the avg competence levels to be sooooo low.

Here's the two nerfs to choose from:
- Same price
- No shock

or
- More expensive
- Bolt lights aren't disabled

I honestly think shocking doors is the kicker here. It's a stun, and stunning allows borgs to shit on people, and it slows people down more than shocking does. I think it should remain a cheap ability, but not have shock. The door lights being disabled should remain though, because it'll stall people like fuck who can't figure it out without outright killing them.

Shocking should remain as a thing that the malf AI can do manually, to target certain people, especially because it's funny to watch people run into airlocks.

**Comment by Atskadan** [comment]
what if instead of only being used once it could be used multiple times but required CPU for every time
3 times maybe
or 2

**Comment by GunHog** [comment]
Kept the cost at 40, retained the lockdown and reset verbs, removed shocking (_I really did not want to lose that_) and kept the bolt lights on. Still pretty powerful, but it does not require insulated gloves any more, unless the AI hates you enough to shock your airlocks.

**Comment by ghost** [comment]
So wait can you do it over and over once you buy it initially? That would be a great thing. Mass doorcrushing.

**Comment by GunHog** [comment]
Yes, once you pay the 40 CPU, you may open and close doors at your leisure. You need keen timing if you want to use it as a door crush though, as there is a short cooldown to help prevent lag. Electrification status of an airlock is not affected by this module now, so any of them you have shocked before will stay that way.

Do take care to not open important airlocks at the wrong time!

**Comment by ghost** [comment]
I like these changes a lot. Now if we can only get 20 readies and more AIs on artyom we can test it more.

**Comment by GunHog** [comment]
It has been merge ready since the modification. But the vote thread in the OP, while lacking in vote count, does not favor this nerf or the previous one.

Either the initial wave of complaints was a very vocal minority, or they simply decided to adapt and move on.
- I can still add the anti-lag optimizations if this is never merged. I just tossed them in here thinking the poll(s) would be different.

**Comment by Atskadan** [comment]
make a new pr for the optimizations if you want

**Pull request closed without merging**
