### PR TITLE
[MAP] Areas fix

### PR DESCRIPTION
**Pull request by ACCount12**
Every time you work with map, turn on 'Options > Frame Areas'. It makes spotting fucked up areas easier a lot. Maybe it needs to be added to list of NTS coding and mapping standards?

Fixed areas in: sec, maint (2 areas), engi, solars (5 areas), ai core and somewhere else.

### CODE REVIEW

**Comment by RemieRichards** [comment]
This appears to not have been map merged.

**Comment by ACCount12** [comment]
No Java on this PC and downloading Java will take forever.

**Comment by RemieRichards** [comment]
@ACCount12 Valid reason, Fair enough.

**Comment by ACCount12** [comment]
~30MBs of Java is not a lot, but I am there now: http://en.wikipedia.org/wiki/Vilyuchinsk
Inet here is like dial-up.

**Pull request merged**
