### PR TITLE
Added attack cooldowns to some objects

### PR DESCRIPTION
**Pull request by ghost**
Includes:
-Fire axe cabinets
-Captain's display case
-RD's lab cage
-Turrets
-Simple animals
-Space vines

### CODE REVIEW

**Comment by GunHog** [comment]
Do not forget turrets!!!!!!!!

**Comment by Atskadan** [comment]
we really should not do that ever
click cooldown was literally the worst feature ever

**Comment by RemieRichards** [comment]
Click cooldowns should only exist in 2 specific situations:
1. Mob --> Mob Interactions
2. Mob --> Important Object interactions

**Comment by ghost** [comment]
And objects with health

**Comment by RemieRichards** [comment]
If it has health, I'd say it's Important.

**Comment by Atskadan** [comment]
we cant automerge this pr

**Comment by ghost** [comment]
Well, I ran into no conflicts when updating it on my end. Try again, maybe?

**Pull request merged**
