### PR TITLE
Adds new scanner/tagger sprites.

### PR DESCRIPTION
**Pull request by MrSnapwalk**
Adds new sprites for the detective's Forensic Scanner and cargo's Destination Tagger. No more blue blob-scanner 9000!
scannersprites

### CODE REVIEW

**Comment by ghost** [comment]
But are there in-hand sprites? :+1:

**Comment by Dorsisdwarf** [comment]
So, uh, which is which? I'm assuming the one in the Left hand is the forensic scanner?

**Comment by MrSnapwalk** [comment]
@paprka
The in-hands are the generic electronic device ones.

@Dorsisdwarf
The game controller-y one on the left is the Destination Tagger, and the scrolly PDA one on the right is the Forensic Scanner.

**Comment by Atskadan** [comment]
sure

**Pull request merged**
