### PR TITLE
FUCK YOU TABLES YOU CODE-POWER ABUSING FAGGOTS. THIRD ROUND IN A FUC...

### PR DESCRIPTION
**Pull request by ghost**
...KING ROW ENDED THANKS TO YOUR SHITTERY. STOP MESSING WITH THE CODE GODDAMN. PLASMA WINDOWS AND ENGINEERS BUILDING THEM, WITH THE CODE BROKEN? FUCK YOU.

ss 2014-05-14 at 01 37 58

### CODE REVIEW

**Comment by Yakk** [comment]
FINALLY

Thank you basedbus.

**Comment by ghost** [comment]
i literally don't see any problem with removing all of startoad's updates here, if anyone wants to clean this up they can but it works so

**Comment by GunHog** [comment]
What is wrong with plasma glass? Why remove it?

**Comment by RemieRichards** [comment]
@GunHog it's broken as hell.

**Comment by Atskadan** [comment]
and not used anywhere

**Comment by Atskadan** [comment]
is this totally 100% reverted to pre-toadcode?
ie issue free

**Comment by Iamgoofball** [comment]
i don't think he did

if you guys are willing I can look into grabbing BS12's working version

**Comment by Atskadan** [comment]
you can do that if you like

**Comment by Atskadan** [comment]
@paprka it would be nice if you reverted all of ST's stuff some time, since none of it is used and it probably isn't that good

**Comment by ghost** [comment]
Basically what it does is completely revert startoad's little 'additions' and 'fixes' to window and glass code that fucked up placing them on grills and also completely removes plasma glass entirely. Everything else remains unchanged. I'm not a master coder and it's pretty sloppy but I tested a few things (making glass, placing glass/rglass on windows, stacking glass, regeants, etc) and it all seems to work without runtimes or compile errors so I'm just gonna say it's good to go.

**Comment by Iamgoofball** [comment]
@paprka before you do it let me know what you're removing so I'll pick through and see what we got fixes for on other branches

**Pull request merged**
