### PR TITLE
More Posters Redux: Code Jesus Take The Wheel Edition

### PR DESCRIPTION
**Pull request by JStheguy**
Adds more posters:
ss13raiders

### CODE REVIEW

**Comment by MrSnapwalk** [comment]
PRAISE THE LAWD
Ninja Edit: That means yes.

**Comment by Atskadan** [comment]
are they fixed

**Comment by ghost** [comment]
The ones on-map aren't fixed because the subtyping breaks them

**Comment by ghost** [comment]
ss 2014-06-05 at 04 51 32

i made it better

**Comment by ghost** [comment]
yeah merge this

**Pull request merged**
