### PR TITLE
Upgradeable kinetic guns, small kinetic charge buff

### PR DESCRIPTION
**Pull request by ACCount12**
You can reduce kinetic gun's cooldown by tweaking or upgrading it's thermal exchanger. 
Maximally upgraded gun's cooldown is 8, standard is 20.

You can increase kinetic gun's range with plasma sheets (up to 5, current is 3), but this can make your gun unsafe.

Kinetic charge is buffed a bit and can damage structures and turfs around the kinetic blast (but not station walls or mobs). This makes kinetic guns a bit better in mining.

### CODE REVIEW

**Comment by RemieRichards** [comment]
I really like how you use lists to add little upgrades to things :+1: 
However, may I request that the upgrades list var be moved to /weapon so it doesn't need redefining for each future upgradeable weapon?

**Comment by ACCount12** [comment]
Not sure there will be other upgradeable weapons.

**Comment by RemieRichards** [comment]
Regardless of whether you think that, People may want too in the future, so it's worth it.

**Comment by ACCount12** [comment]
Then we will need a system for upgrades with upgrades datums and blah blah.

**Comment by RemieRichards** [comment]
I won't push you that far for this PR.

Ready for me to merge?

**Comment by ACCount12** [comment]
Yep. There is a small fix PR incoming, but it is unrelated to kinetic guns.

**Pull request merged**
