### PR TITLE
Adds clothing vendor

### PR DESCRIPTION
**Pull request by ike709**
Todo:
1.Add a few of these to Metastation: Done
2.Do lots of tests for bugs: Done
3.Finalize items/quantities: Done

Adds Clothe-O-Mat, a machine that provides both normal and formal clothes (Unlike the autodrobe, which is for costumes.) No access is required and it includes items that require either a coin or hacking it to acquire.
Credit to JStheguy for the sprites: http://i.imgur.com/bKZ269Q.png (broken/unpowered not shown)
Also: Yay for first actual feature!

### CODE REVIEW

**Comment by ghost** [comment]
neet

**Comment by Tokiko1** [comment]
Replace the maid costume with the uniform maybe?

**Comment by ike709** [comment]
@Tokiko1 Theres a difference?

**Comment by Tokiko1** [comment]
One is blue, one is black and short sleeved. The costume one is also already avaible in the autodrobe.

**Comment by ike709** [comment]
@Tokiko1 I'll fix it tomorrow

**Comment by ike709** [comment]
Unless anyone else has feedback, this is merge ready.

**Pull request merged**
