### PR TITLE
Adds the Guy Fawkes mask to Autodrobe and spawn

### PR DESCRIPTION
**Pull request by UncleSporky**
front
side

### CODE REVIEW

**Comment by fleure** [comment]
Ew. _Ew_.

**Comment by Atskadan** [comment]
<i>why</i>

**Comment by Incoming5643** [comment]
Know now the price of universal acceptance.

**Comment by Petethegoat** [comment]
The sprite actually looks great.

**Comment by RemieRichards** [comment]
Remember Remember the 5th of November.

**Comment by Iamgoofball** [comment]
do we really need this?

**Comment by UncleSporky** [comment]
I believe it to be completely necessary!

I just think it'd be fun.  Mercilessly mock the people who wear it and refuse them service until it comes off.

**Comment by Atskadan** [comment]
we already have a fedora : ^ )

**Comment by UncleSporky** [comment]
The other thing I was going to work on was protest signs, and the mask immediately came to mind.  I guess the appropriateness of protest signs could be debated elsewhere, and I could include this in that PR instead, if/when it happens.

**Comment by Iamgoofball** [comment]
make it glued on just like with the horsehead mask

**Pull request merged**
