### PR TITLE
Colored and clear glasses

### PR DESCRIPTION
**Pull request by ghost**
ss 2014-05-23 at 04 55 58

Could someone do me a favor and code these to work with the washing machine? Not sure how that works but here you go, the items, and all the crayon colors, with a few extra.

### CODE REVIEW

**Comment by RemieRichards** [comment]
The washing machine is ancient TERRIBLE code, not even erro who wrote it is willing to touch it.

**Comment by ghost** [comment]
Bursts into treats.

**Comment by RemieRichards** [comment]
> treats

**Comment by Atskadan** [comment]
that is the joke

**Comment by RemieRichards** [comment]
_flails arms_

**Comment by ghost** [comment]
it has something to do with item_color as in the green glasses would be item_color and washing glasses just makes them use the icon state or 'item color' greenglasses, it's really weirdly complicated though, not sure if anyone can decode it but i don't have the time currently

**Pull request merged**
