### PR TITLE
Adds MediPen to 'survival' box (default spawn box)

### PR DESCRIPTION
**Pull request by JJRcop**
I added one MediPen to the default spawn box, in hopes that it helps when you discover a person in critical condition, so you can get them to appropriate medical care.

### CODE REVIEW

**Comment by ike709** [comment]
I like it

**Comment by ghost** [comment]
:+1:

**Comment by ghost** [comment]
Basically makes CPR useless once people git gud though

**Comment by JJRcop** [comment]
Not exactly, CPR heals oxyloss, while Inaprovaline merely prevents it from getting worse.

**Pull request merged**
