### PR TITLE
Move config files from config/ to config/example/

### PR DESCRIPTION
**Pull request by mloc**
Moves all the game config files from config to an example subdirectory.
When people first clone the repo, they will need to copy files from
config/example into config, but this will only need to be done once
barring any `git clean` calls.
This allows developers to keep their admins.txt persistent, and allows
easy modification of the example files without having to reset.
README.md updated and .gitignore added for config.

### CODE REVIEW

**Comment by Petethegoat** [comment]
:heart:

**Comment by Iamgoofball** [comment]
Copy the contents of old admins.txt into the new one, please.

**Comment by Atskadan** [comment]
We can’t automatically merge this pull request.

**Comment by Atskadan** [comment]
@mloc

**Comment by Petethegoat** [comment]
If /tg/ aren't going to merge it, then it might be more trouble than it's worth.

**Comment by Atskadan** [comment]
@mloc !!!

**Comment by Atskadan** [comment]
no response, closing until he comes back

**Pull request closed without merging**
