### PR TITLE
Dismemberment [Fuck yeah Edition]

### PR DESCRIPTION
**Pull request by RemieRichards**
Melee Weapons with Sharp and Guns can now Dismember limbs.

Comes with a new Human Icon Cache system which ensures human mobs only create new image objects when absolutely necessary, as to reduce the cost of human icon updates involving limbs

Augmentation surgery removed, This will be replaced in a later PR with a simple Removal surgery, for now, Use a Surgical saw to just hack the limb off.

All limbs can be "removed" however The head can only be removed surgically (IE, impossible atm)

Only the Arms and legs visibly show themselves to be removed due to the Head and Chest being exceptions.

Augments are a separate item to Cyborg parts, and can be built from the Robotics/Mech Fabricator.

Testing has resulted in 0 Bugs. No bugs. Magic.

### CODE REVIEW

**Comment by Dorsisdwarf** [comment]
Guns can cause dismemberment? So you can shoot security's arms off with your carglocks?

**Comment by RemieRichards** [comment]
@Dorsisdwarf Totally.

**Comment by ghost** [comment]
https://www.youtube.com/watch?v=WRu_-9MBpd4

**Comment by ike709** [comment]
@RemieRichards Can augments be cutoff/shot off? Also, don't forget to add this to the changelog so people don't start spamming ahelp when guncargo shoots their limbs off.

**Comment by RemieRichards** [comment]
Yeah Augments are still limbs so they get shot off/cut off too.

Changelogs come after the main PR these days as not to cause conflicts.

**Comment by Dorsisdwarf** [comment]
If you have no legs, you can't move right?

**Comment by RemieRichards** [comment]
@Dorsisdwarf 
Missing one leg = Move slower
Missing both legs = No Moving

**Comment by ike709** [comment]
But can't they just pull themselves forward with their arms if they have no legs?

**Comment by RemieRichards** [comment]
@ike709 No, it doesn't look good.

**Comment by GunHog** [comment]
Loving this, RR! :D

**Comment by Steelpoint** [comment]
What does it take to dismember a limb? In addition does Armour protect against dismemberment.

In addition, do certain antagonists (Aside from the Changeling) have a recourse to losing a limb. A Wizard losing their leg is screwed since they will have little recourse.

I love the change, I just wish to know more about the mechanics, and I can't into code easily.

**Comment by RemieRichards** [comment]
@Steelpoint to dismember a limb you must take it down to half it's health (Limbs have health individually and it all adds to make the "Health" that humans have) Considering the main requirement is damaging the limb, armour does have an impact yes also the Weapon must also be sharp (If it's a melee weapon)

**Comment by RemieRichards** [comment]
@NTStation/contributors This is merge ready, btw. May want to do some testing with @GunHog as he always seems to find the most edgiest of edge case bugs.

**Comment by Atskadan** [comment]
then let gun hog test

**Comment by Lumipharon** [comment]
Most guns aren't really powerful enough to blow someone's limbs, and it seems a bit odd to imagine someone with a scalpel hitting you in the leg a few times and it just falls off.

Surely it would need to be something powerful enough to go right through the bone (ie: saw)?

**Comment by RemieRichards** [comment]
@Lumipharon scalpels don't do much damage, you need to damage the limb to atleast half it's health first, I think that's fair balance.

**Comment by JJRcop** [comment]
@RemieRichards @Lumipharon Think of it as the half damage means the leg is already pretty badly cut up, maybe the muscle is very well cut into and the bone is already visible. It isn't coming off any time soon, but it can be torn off with something sharp since you have direct access to the bone already, you can fracture it with the scalpel and off it goes.

**Comment by Tokiko1** [comment]
Is there any way to heal brute damage to stumps? I spawned a human, chopped off the arms with that new katana and they were effectively permacritted as the total damage was 75 and 50 brute damage and medicine didn't seem to work on them. Maybe allow dismembered limbs to be healed down to 25 brute? That way doctors can actually do something and keep people concious before getting them new limbs.

Also not sure if this was fixed yet, but dismembering a leg should remove any socks the character is wearing aswell.

**Comment by RemieRichards** [comment]
@Tokiko1 I really don't want to have to mess around with healing minor damage on a limb.
at present, depending on the damage of the weapon, 2 limbs missing or more is fatal.
1 limb will always be survivable. I feel it's fair due to adding a new limb instantly healing the damaged limb (due to it being "new") which means someone in crit can instantly be brought back by replacing their limbs.

Also, on socks:

```
    if(socks)
        if(get_num_limbs_of_state(LEG_RIGHT,ORGAN_FINE) >= 2
```

So they only render with 2 or more legs (The last commit actually has it listed as ORGAN_REMOVED which is wrong)

**Comment by Lumipharon** [comment]
I'm just saying like, could you punch someone in the arm repeatedly, then whip out a scalpel/kitche knife, and lop off the arm since it's under half health?

Also won't revolvers be able to like, blow people's limbs off with a single hit?

Don't get me wrong, I want to see dismemberment, I just don't want to see limbs flying off constantly in slightly absurd circumstances. Oh, and can you pick up your limb, and carry it to medbay to have it stiched back on or something?

**Comment by ike709** [comment]
> pick up your limb

slaps the clown with his arm

**Comment by ike709** [comment]
pls merge before update tonight EDIT: 2late T_T

**Comment by ike709** [comment]
Can cutting out tongues be added aswell? It'd be a good way to shut annoying people up.

**Comment by RemieRichards** [comment]
@Lumipharon 

> I'm just saying like, could you punch someone in the arm repeatedly, then whip out a scalpel/kitche knife, and lop off the arm since it's under half health?

Yes, that's entirely possible, but if you can successfully punch somebody's limb to 50% of it's health, AND swap to a scalpel AND the rng chance of it chopping the limb off (which is the strength of the weapon, so in scalpel's case is low) Then you deserve that dismemberment.

> Oh, and can you pick up your limb, and carry it to medbay to have it stiched back on or something?

You can pick it up, but you can't have it reattached yet, I intend to do organic replacement limbs later down the line, probably like how goon does it (with a medical staple gun) At the moment, the only replacement limbs are the augment limbs.

**Comment by Steelpoint** [comment]
It would be interesting to explore being able to reattach someone's own limb if done in a certain time frame.

For example, when a limb is detached it has a 2 minute compatibility time frame where you can reattach it. Placing the limb inside a mobile cooler (New Medical Item) would increase this time frame to 6 minutes.

**Comment by RemieRichards** [comment]
@Steelpoint a time frame and mobile cooler sound like interesting concepts, I'll incorporate them once I start on Organic replacement of limbs. 

I intend to do what goon does as ell and have limbs NOT belonging to the right person causing issues, with no system for internal organ failure at the moment I'll probably cause the replaced limb to start off damaged.

**Comment by Lumipharon** [comment]
Make it a cryo jar, so you can see the head/arm/leg floating about inside. Maybe with a little expiration date on it, if you examine it, or something.

Also, is it possible to blow a limb off with a hit that takes that limb under 50% health, or does the limb have to be under before that? Because rng blowing peoples limbs off with a revolver will be pretty awful, if somewhat hilarious.

**Comment by RemieRichards** [comment]
@Lumipharon there are 2 formulas for working out whether an attack dismembers a limb.

if it's a melee attack, then the formula checks to see if the current damage taken + the melee weapon's damage is above half health.

if it's an explosion or a gun, it just checks for half damage on the limb.

**Comment by Lumipharon** [comment]
So that's a yes? Hm, will be interesting to say the least.

**Comment by Tokiko1** [comment]
Can we get this merged before the server updates again? Really looking forward to seeing it in action.

**Pull request merged**
