### PR TITLE
Summon Mechs/Summon Melee [MERGE DIS]

### PR DESCRIPTION
**Pull request by RemieRichards**
Renames "rightandwrong" Who on earth named it this and WHY? it's stupid.

Summon Mechs and Summon Melee.

Mechs summoned by summon mechs do not have access requirements, due to some of the more powerful mechs starting with access requirements. Summon Mechs costs 2 uses per purchase, due to it's power.

Summon Melee costs 1 use per purchase, like the other normal "Summon X" powers.

Added /loaded varients of most (All?) Mechs that need to spawn with equipment (The seraph is an exception, it's Normal variant already has equipment)

Idea blatantly stolen from paprika :)

(Paprika's) Poll:
http://tgstation13.org/phpBB/viewtopic.php?f=15&t=453

### CODE REVIEW

**Comment by Atskadan** [comment]
>summons mechs
jfc

make summon melee change the click delay to april fools too

**Comment by GunHog** [comment]
Oh yes, I love this. Also "rightandwrong" is a reference to a comic in which a wizard conjures and gives out loads of guns. You do not really need to rename it. PLEASE keep the mechs in! As a Wizard, I would LOVE to activate ALL FOUR SPELLS and get a scrying orb to see how much chaos this can cause.

**Comment by RemieRichards** [comment]
Actually :@GunHog that's impossible, Summon mechs costs 2 charges and you start with 5 so
Summon Mechs -2
Summon Guns -1
Summon Melee -1
Summon Magic - 1
Scrying orb -1
Leaves you at -1 points. You'd have to miss out on one of the Other spells to see the chaos.
And interesting to know it's to do with a comic, References are fine, but when an entire function/proc is named as a reference, it's hardly helpful.

**Comment by Iamgoofball** [comment]
Eh, I'd make it cost 1, BUT, it should summon Ion Guns along with each mech, so it doesn't just easily become mechadrome

**Comment by Atskadan** [comment]
summon melee needs way more items too
when #579 gets in you could add all of those (and the guns to summon guns)
stuff like stun batons, police batons, stun prods, booze bottles, kitchen knives, etc
lots of improvised weapons and stuff

@iamgoofball that would remove the entire point of summoning mechs
its for mech battles, not ion gun battles

**Comment by RemieRichards** [comment]
@Atskadan 's Point holds @Iamgoofball Plus it really REALLY cannot get cheaper than 2, 2 is fucking cheap for every bastard on the station getting a mech.

And yeah, Melee is a bit limited atm

**Comment by GunHog** [comment]
I would prefer you keep it at one charge.  You do have some powerful mechs here, but you are giving people pulse rifles and staffs that transform people instantly. Summon Mechs is only too much if it is the only spell the wizard used. If you tack Summon Guns or Magic on it, those mechs are going to have a hard time. I am agreeing with Goofball on the cost here.

**Comment by Iamgoofball** [comment]
@RemieRichards Arguably some of the guns you can summon with summon guns are ten times more powerful then mechs.

**Comment by RemieRichards** [comment]
Tell that to 30 mechs of Durands and Gygax's including atleast 1 Seraph, Marauder and Mauler and Phazon

I refuse to believe that a 1 cost is Balanced. a wizard should not be able to buy Summon Mechs 5 times! that's Absurd. 2 purchases now (5-2-2 = 1) Is pushing it already.

**Comment by Iamgoofball** [comment]
> Summon Magic
> EMP Book
> Spam EMPs near mechs

I think we should do a test run on 1 and 2 settings, to see what will happen. We don't know what will happen until we have tested it.

**Comment by RemieRichards** [comment]
With quite a few wizards having a laugh with 5x summon guns and 5x Summon magic it's safe to say people would go mental with 5x Mechs.

**Comment by GunHog** [comment]
Agreed with Goofball. Also, this is Wizard. NOTHING about Wizard is balanced. One guy gets a puny little taser, and another gets a bloody pulse rifle. It is all about CHAOS, and all of the summon spells achieve this in their own way. Going mental is what you WANT.

The station should look as if HBL logged on the server while in a very bad mood.

**Comment by RemieRichards** [comment]
I can't dispute that point @GunHog 

I suppose a test such as @Iamgoofball suggests would be fine.
But it is most assuredly being merged firstly with a cost of 2. I won't budge on that front.

**Comment by ghost** [comment]
Taser is mightier than the pulse. Pulse guy keeps his gun on destroy like a stupid bloodthirsty newbie, gets tased, and now taser guy has two guns.

Also fucking RR this is amazing keep it up I have never had an idea as good as this.

**Comment by RemieRichards** [comment]
@paprka 

> Idea blatantly stolen from paprika :)

:)

**Comment by drynwyn** [comment]
No point in 5x or 2x summon mechs. You can only use one mech at a time.

**Comment by ghost** [comment]
Some men just want to see the station covered in mechs, is that so bad? There WILL be someone who uses 2x summon mechs, I guarantee you.

**Comment by GunHog** [comment]
Thing about mechs is - once destroyed, they will be useless. And yes, there will be lots of empty mechs around. Mechs that will be used once the others are destroyed. If the Wizard summoned ONLY mechs, then you are probably boned once you lose your mech.

**Comment by RemieRichards** [comment]
@drynwyn With the fact that ALL and I mean ALL mechs are in the rotation, you can end up with a pretty rubbish combat mech, Eg. Odysseus or Ripley. Ideally a Wizard would use both so that they get a "Reroll"  on their mech, and also everyone on station does. it's too add to the madness, plus if everybody has 2 mechs (you'll probably immediately DNA lock both because Powergamers) then it'll be a lot more chaotic.

**Comment by RemieRichards** [comment]
get me sprites and wizard mech are go.

**Comment by drynwyn** [comment]
The phazon already looks like a wizard's mecha, it's in line with the color scheme and general appearance of the hardsuit.

**Comment by RemieRichards** [comment]
Hardsuit = Purple
Phazon = Blue

Not even a similar Shade, and no the phazon does not wizardy at all, it's just advanced tech.

**Comment by drynwyn** [comment]
Recoloring is easy, I meant the shape of it.

**Comment by Yakk** [comment]
Do these spells add "survivors" to the round? I haven't seen people immediately murderbone after a summon mechs spell so I'm thinking that it does not.

**Comment by RemieRichards** [comment]
@Yakk You'd be wrong then Yakk. It's the same Spell as Summon Guns and Summon Magic, they've always been the same spell, now there's just 4 of them within the same spell, and Survivors have always been a 1/4 chance not guaranteed.

**Pull request merged**
