### PR TITLE
Removes HoP's helmet

### PR DESCRIPTION
**Pull request by ghost**
What it says on the tin. Removes the helmet from spawning HoPs and the one in his locker. The intent was to reduce the perception that the HoP is a combat-oriented role and further discourage and make more obvious of HoPs who powergame/HoPcurity.

Questions or concerns are welcome.

### CODE REVIEW

**Comment by ghost** [comment]
I'm going to give 6-8 hours and if no one refuses then I'll merge.

**Comment by Atskadan** [comment]
i object
im at school so i dont have access to the forums right now but i already expressed my opinions there

**Comment by ghost** [comment]
How about this. We make some new, slightly weaker armour. Like this but not
black. http://www.ppss-group.com/ppss_images/overt_body_armour.jpg

**Comment by ghost** [comment]
I'd like to hear your thoughts on why you think the HoP needs armor at all.

**Comment by ghost** [comment]
He posted here Ikarrus.
http://www.ss13.eu/phpbb/viewtopic.php?f=42&t=9&start=1800#p117930
If he is Miggles and I'm like 99% positive.

**Comment by ghost** [comment]
As I posted there, armor plays no part in carrying out any of those things Miggles mentioned. You don't need armor to check on the crew. You'd only need it if you were looking for trouble (ie HoPcurity)

**Comment by ghost** [comment]
I've updated the PR to only remove the security helmet after considering the feedback I've received. please let me know if this is more acceptable.

**Comment by RemieRichards** [comment]
Ikky, Can you remove the lines instead of commenting them out?
if you want to add them back in the future (of this PR) just revert that commit.

**Comment by ghost** [comment]
sure

**Comment by RemieRichards** [comment]
Right, all my concerns are dealt with
Down with commando hop :+1:

**Comment by Iamgoofball** [comment]
Bonus merge points for the PR, Ikarrus, if you and Nienhaus make the Papers Please hat for the HoP as the helmet replacement.

**Comment by Iamgoofball** [comment]
But then again a daylong poll is probably a good idea.

**Comment by akenworthy87** [comment]
Armored clothing like the detective's coat / wardens jacket would be a good replacement.
A pallet swap of the warden's jacket would probably fit nicely with an armored cap.

**Comment by Neerti** [comment]
But he wants the hop to have no armor at all whatsoever.

**Comment by ghost** [comment]
What I want is different from what I am proposing here. I understand that my opinion is mine alone and that compromise is what is needed here.

**Comment by Atskadan** [comment]
I'm fine with this if you add the hat and such from the PR on /tg/

**Comment by Steelpoint** [comment]
Personally I appreciate anything that helps cut down on "HoPcurity". I still advocate that the HoP be reworked to be a Lieutenant.

**Comment by ghost** [comment]
Anyone know of an easy way to get my commits to my TG fork over to my NT fork? I don't want to be having to clone a whole new repo just to make the same changes I did already.

https://github.com/tgstation/-tg-station/pull/3058

**Comment by Atskadan** [comment]
just copy the files from your tg fork and paste them in your nt fork and commit?

**Comment by ghost** [comment]
I just said I don't want to be doing just that if I can help it.

**Comment by Atskadan** [comment]
ah, right. i didn't realize what you were saying.
if you just commit the changes to your /tg/ fork, why can't you do the exact same to your nt fork?

**Comment by ghost** [comment]
Because git is a complex woman with very specific needs. She just won't accept any straightforward advance. At least, not one that I can comprehend yet.

**Comment by KazeEspada** [comment]
I dont support removing the helmets due to the stun protection, but i do like removing the helmet for a less armored hop. Give him a light helmet.

**Comment by Neerti** [comment]
I hate the helmet sprite so I just remove it anyways.

If I'm sec, beret stronk.

Also would it be too much to ask to get the new hat and uniform that's in your PR on /tg/station?

**Comment by Steelpoint** [comment]
Difference is the Captain can quickly and easily substitute their hat for a SWAT Helmet, one of the most protective Helmets in the game.

I would argue that either the HoP is given a Cap like Hat that gives Helmet Style Protection, or change his title to Lieutenant so he has an excuse to wear armor.

**Comment by ghost** [comment]
@Neerti please read my comments above.

**Comment by akenworthy87** [comment]
Its okay Ikky, its not like you guys have a stranglehold on how things are committed anymore. 

## We can always change it if we feel like it.

-----Original Message-----

**Comment by ghost** [comment]
Well, that is the benefit of working open source, but your needlessly hostile threat has been noticed.

**Comment by ghost** [comment]
I'm just going to go ahead and close this since people are getting the wrong idea of what I'm trying to accomplish here. If and when I can figure out an easier way to port changes I push to TGstation I may try again.

**Comment by akenworthy87** [comment]
Well it is nice to be noticed!

I'm just telling you how it is Ikarrus - you being part of the coderbus elite doesn't mean jackshit here.
This isn't a branch where you're going to be able to force down needless nerfs without fear of giving a damn about player feedback.

**Comment by ghost** [comment]
I'm not attempting to force anything down anyone's throat? This whole PR I've been trying to gather feedback and reach a compromise here. Not everything has to go your way, or my way for that matter.

I really can't help but feel that you're still just upset towards me that I reverted your change to the HoP office.

**Comment by ghost** [comment]
I like the idea of the new outfit. I know I can't wait to use it on /TG/

**Comment by ghost** [comment]
If the members of this branch know how to pull the changes from the TG branch, then it would probably be easier (and faster) to do that instead of waiting on me to make a new PR.

**Comment by Iamgoofball** [comment]
I was gonna merge this today. Oh well.

**Comment by ghost** [comment]
@iamgoofball
You're welcome to pull the changes from tg, though. They just merged it.

**Comment by Iamgoofball** [comment]
Ah, alright.

**Comment by akenworthy87** [comment]
Any reason you've deleted some of your posts Ikarrus, particularly the one which was a response to Steelpoint which I in turn replied to?

Yeah I'm still a bit irked that you reverted my HoP office change - wouldn't you be POed that something you worked on for two months was removed completely without a single trace. 
Funnily enough that was also to stop HoPs acting like self entitled dicks by removing his protective bubble, something which might actually work - unlike this because HoPcurrity is going to grab the armour and helmet the same time he grabs a sec hud.

Now if that was the only thing I would be incredibly petty I would agree, but that's not the only thing, you've done a lot of nerfs I haven't agreed with.
Lets see....
-You divided Sec up so theres barely any organisation or concentration of power.
-You removed a lot of the HoSes access to key areas like the teleporter, RnD, Toxins, Robotics, Atmospherics, and other trouble hotspots.
-You removed the detective's security access so that players that want to play as a police detective need to go through hoops
-You continually weakened the brig walls to the point that its a complete joke to break into the brig
-You made flashers into a relic that sits in the brig collecting dust - as I said would happen.
-You made borgs practically useless for a subverted AI.

**Comment by Atskadan** [comment]
Malkevin, stop. If he wants to make some changes, then he can. You're being needlessly hostile. This isn't YOUR codebase, it's EVERYONE'S. It's open source, just as you said. Driving people off because you don't personally agree with them is not how things should be done.

**Comment by akenworthy87** [comment]
Okay Miggles, I'll be quiet and let nerfs continue to get merged, just like the old code base.

Maybe it escaped your attention but I was one of the only coders that bothered to fight against coderbus making crap changes that no one wanted or asked for. Majority of things I argued against players then later argued against, so its not like I was arguing for my own sake.

Just like you argued against the HoP loosing his armor and helmet because he's a high value target and needs protection. In case you didn't notice, that went through on the main branch. The HoP now has only a vest in his locker and an unarmoured hat.

**Comment by Iamgoofball** [comment]
Everyone take a chill pill. I'll tally up the yea-nea votes soon.

**Comment by Atskadan** [comment]
I wasn't against the HoP losing his helmet, only the armor vest, which he still has, as well as new clothes. The benefits outweigh the odds here IMO. If you want to get your powergamer HoPcurity helmet you can always take one from the sec checkpoint.

Nerfs aren't ALWAYS a bad thing and this is hardly even a nerf since the HoP doesn't even need a helmet.

**Comment by sippingmariowater** [comment]
Suggestion:
Make the HoP hat have the same armor as the HoS hat (or maybe slightly less.)
replace the helmet with this

-danno

**Pull request closed without merging**
