### PR TITLE
reverts changes to schoolgirl uniform they were dumb

### PR DESCRIPTION
**Pull request by Atskadan**
yeah

### CODE REVIEW

**Comment by ghost** [comment]
I knew this would happen.

**Comment by Atskadan** [comment]
before: good
after: bad

i literally just made the side view 2 pixels skinnier and it didnt look good so i want it back to the way it was
i didnt change anything else

**Comment by Iamgoofball** [comment]
Unless we download the file and check, or you show a comparison, this  PR could of replaced every sprite in the file with goatse.

**Comment by Atskadan** [comment]
if youre that stupid to think that then download the file and check

**Comment by ghost** [comment]
miggles made the schoolgirl uniform have a big boner sticking out under this skirt in this pr do not merge

**Pull request merged**
