### PR TITLE
Fixed genetic spells ('Mutate' from wizard)

### PR DESCRIPTION
**Pull request by ACCount12**
USE CODE TESTING USE CODE TESTING USE CODE TESTING

### CODE REVIEW

**Comment by RemieRichards** [comment]
Any particular reason as to why it didn't work before?

**Comment by ACCount12** [comment]
When using for(var/datum/D in list), you will loop over all /datum typed objects in list. But not over 'type' vars and not over 'text' vars with /datum types inside.

**Comment by RemieRichards** [comment]
@ACCount12 But it wasn't pure datum, it was typecasted to what it should have been?

I'm not concerned with anything, this will get merged, I'm just curious as to why it didn't work before.

**Comment by ACCount12** [comment]
var/list/mutations is list of types, not datums. And even if it was list of datums, it will not work. add_organic_blah_blah() accepts only types AFAIK.

**Comment by RemieRichards** [comment]
Are you sure? 

```
/mob/proc/add_organic_effect(var/PATH)
    if(!ispath(PATH))
        return
    var/datum/organic_effect/OE = new PATH
    organic_effects += OE
    OE.owner = src
```

**Comment by ACCount12** [comment]
```
if(!ispath(PATH))
    return
```

If it is not path (aka type), function returns.

**Comment by RemieRichards** [comment]
That wasn't really the point I was getting at, You say it's a list of Types, yes? But this list is only added to after a New, Which means the datum exists, meaning the list should be a list of datums, and not a list of types.

**Comment by ACCount12** [comment]
var/list/mutations in spell is list of types
var/list/organic_effects is mob is list of datums

**Comment by RemieRichards** [comment]
Oh bugger! The list is Mutations! Sorry, God what the hell was I thinking when I wrote that.

I think that the Mutations list there should probably be the organic_effects list though.

**Comment by ACCount12** [comment]
Merge?

**Pull request merged**
