### PR TITLE
Github: The returning

### PR DESCRIPTION
**Pull request by StarToad**
Includes some fixes. Nothing much. And removal of the custom drinking glasses. :( Maybe i'll fix them later.

### CODE REVIEW

**Comment by Iamgoofball** [comment]
We can't automerge this, I'd try pulling from master upstream and see what conflicts.

**Comment by StarToad** [comment]
I'd do it if I had any idea on how to do it :V

**Comment by Iamgoofball** [comment]
rightclick your folder provided you're using tortoisegit
go into Git->Pull
set remote to https://github.com/NTStation/NTstation13.git
set branch to master
proceed with pulling
go to the files that it said conflict
look around in the file for the >>HEAD thing
remove anything that was added by git
push to your branch

**Comment by KazeEspada** [comment]
Also, can you fix the issue that i mentioned in the last pull is with ismob() || isturf() || isobj because that should really just be one istype(target,/atom) or /atom/movable

**Comment by StarToad** [comment]
As it turns out it didnt fix it, but then again one of the proposed fixes for the deaf bug on tg didn't either, so.

**Comment by Iamgoofball** [comment]
did you commit or push after you pulled?

**Comment by Iamgoofball** [comment]
Alright well you should probably remake the PR on a new branch and try it again, I don't know why it won't automerge.

**Comment by Iamgoofball** [comment]
shit didn't mean to close it

fuck I can't reopen it
shit

**Comment by Atskadan** [comment]
It needed to be fixed either way.

**Pull request closed without merging**
