### PR TITLE
Adds Nightvision Security and Medical HUDs!

### PR DESCRIPTION
**Pull request by GunHog**
This update combines the function of night-vision goggles with Medical and Security HUDS.

Both HUDs include the base cost of the night-vision goggles item, plus additional tech and mineral requirements.
- Silver is required for the medical NVG HUD, with a bio tech requirement of 4.
- Gold is required for the security NVG HUD, with a combat tech requirement of 4.
- The electromagnetic spectrum tech requirement for them both is 5, regular NVG remain at 4.
- Like the standard security HUD, the night-vision version also comes in a lockbox.

*Please note that the night-vision security HUD lacks the flash protection and welder eye damage reduction of the typical HUD sunglasses that most officers wear. As such, officers will need to make a tactical choice on which type to wear!

Sprites by Nienhaus!
screenshot 2014-04-25 12 06 43

### CODE REVIEW

**Comment by Atskadan** [comment]
it would be cool if they looked like NVGs with differences instead of scanners with differences

**Comment by ghost** [comment]
He said he wanted scanners so that's why I did them.

**Comment by GunHog** [comment]
I like the scouter look!

**Comment by Atskadan** [comment]
ok

**Pull request merged**
