### PR TITLE
Changes the Boozepwr of drinks

### PR DESCRIPTION
**Pull request by Atskadan**
so you don't become a stuttering mess so quickly

these values are easily changed so feel free to suggest different ones

### CODE REVIEW

**Comment by ghost** [comment]
can you add breathalyzers for sec so we can brig people for being too drunk on the job

**Comment by vista-** [comment]
To be honest, I haven't encountered any problems with booze strength, you have to drink like, more than 75 units of beer to become a stuttering mess.

**Comment by Atskadan** [comment]
yeah a single drink of pretty much any alcohol out of the bottle will make you drunk
honestly i dont think these values are even enough

**Comment by Petethegoat** [comment]
Vistapowa it's delayed basically. Pretty sure one sip of spacebeer will fucking wreck you forever, when it kicks in after a minute or two.

Like how if you eat a single donut at roundstart you're fucked fat forever gg no re good luck walking that off fatty

**Pull request merged**
