### PR TITLE
Rusted Walls

### PR DESCRIPTION
**Pull request by JStheguy**
-Adds rusted walls and rusted rwalls, they function like their non-rusted counterparts but are slightly weaker to hulk attacks and have a rusted appearance.
-Replaces walls and rwalls on the Derelict, the Ruskie DJ Station, the Abandoned Telecomms Satellite, the Abandoned Mining Outpost, and the various teleporter rooms in space with the rusted variants.
ss13gruelvendor

### CODE REVIEW

**Comment by GunHog** [comment]
I am loving the look, but I have to wonder...how do the walls rust if they are exposed to space?

**Comment by Atskadan** [comment]
space oxygen
it is everpresent yet unbreathable by humans

**Comment by ike709** [comment]
I don't think the Ruskie DJ Station should be rusted, it's not exactly abandoned like the Derelict.

**Comment by ghost** [comment]
10/10 it's okay

**Comment by validsalad** [comment]
http://i.imgur.com/gygq3Tp.png

I had these sprites sitting around, doesn't matter if they're used or not but if they are, please note there are extra W-E and N-S wall sprites that can be used to add a bit of variation.

**Comment by ghost** [comment]
why is it every time someone makes a sprite valid comes in and blows them out of the water

**Comment by Atskadan** [comment]
because valid is a meanie >:c
but no really gud jorb valed

**Comment by JStheguy** [comment]
Wait I think those sprites were made by ausops weren't they?
Fuck valid are you one of his 20 usernames?

**Comment by Atskadan** [comment]
this is old news JS

**Comment by Atskadan** [comment]
could you try rusted floors too?

**Comment by Atskadan** [comment]
oh well

**Pull request merged**
