### PR TITLE
Readds the gag ball

### PR DESCRIPTION
**Pull request by CobaltAnt**
This was an item removed for no good reason by coderbus, and was voted for by the community to stay/be readded.

Original removal pull request here: https://github.com/tgstation/-tg-station/pull/2214

### CODE REVIEW

**Comment by ghost** [comment]
I'm going to merge this.

**Comment by CobaltAnt** [comment]
Thank you for the prompt merge! For my next pull request I'd like to expand upon this one, I think some more latex clothing, or possibly riding crops would be a great addition.

**Comment by StarToad** [comment]
Pls no. Save that for April Fools if anything.

**Comment by theOperand** [comment]
ntstation will soon become erpstation

**Comment by ghost** [comment]
Yeah I don't think any of that other stuff is going to be added. Atleast I
know I'm not voting for it.

**Comment by StarToad** [comment]
I hope not, we really don't need more ERP/Bondage stuff ffs.

**Comment by Iamgoofball** [comment]
"riding crops"
"latex clothing"

i will personally revert and close those PRs

**Comment by ghost** [comment]
I do remember a ton of people freaking out.

**Pull request merged**
