### PR TITLE
Hairsprite update

### PR DESCRIPTION
**Pull request by ghost**
Another one.

I updated the overeye in this one, and here's the differences. I like the way the 'fringe' hairs approach hairsprites, in that they show the ear and they also round the hair on the west/east facing sprites in a way that looks ultimately more natural. The fringe hairsprites are shaded like shit and I think ikkarus updated this at some point but it was reverted because it didn't look good in the end or something, i'm not sure.

Anyway here's the before and after alpha of my changes to the overeye hairs:
sdfd
(this is the old overeye_short i made a while ago and on the left is long fringe, not the current one, but i used the hair as reference for the changes)

I'm not sure why I've taken so much time tweaking hairs here and there, I guess there's been little visual issues in some hair sprites that bug me and make them shit to look at from different directions, like how i changed ponytail 3. And hair is really one of the fastest identifiers of someone (snowflake identifiers!!) so I wanted to at least make some changes to make them look a little bit nicer and correct some ancient issues i've had with them.

I'll make more commentary on my edits on the hairs if i end up doing more actual changes to them so people can actually see what I'm doing.

### CODE REVIEW

**Comment by WJohn** [comment]
More hair and style will always get a :+1: from me.

**Comment by ColonicAcid** [comment]
I need to learn how to get to the hair sprites because some of them are pretty meh tier.
Like a lot of the old ones.

**Comment by ghost** [comment]
just open up human_face or whatever, all the hair sprites are in there. I'd really like a team of people with sprite knowledge to go through and spruce them up, maybe make them more uniform and organized.

**Comment by Atskadan** [comment]
could you look at the curls hair? i think it actually looks good, but not really curly. could you try and make a different hair based on that that's more curly?

**Comment by ghost** [comment]
I just wanted to spruce up the hair sprites i added atm so no do it urself :hamburger:

**Pull request merged**
