### PR TITLE
[MAP] Updates potted plants and assistant spawn locations + more stuff!!

### PR DESCRIPTION
**Pull request by ghost**
- Added DEEP LORE descriptions to almost all the unique potted plants.
- Made the engineering potted plants and solars potted plants glow a tiny bit for when engineering's lights get blown out **AGAIN**
- Moved some potted plants around, added some more. It's still not plantstation13, tho.
- Fixed cargo plants not being on the right layer, you can hide behind them now.
- Moved assistant spawn locations all over the map, so now they can spawn all over instead of tool storage where they kill each other or mass suicide.

The 'spawning all over' change was one suggested and discussed on the forums, but if it's one nobody likes I will revert it. It seems like a good change from 'everyone spawn in tool storage and blow each other up', though. Yes, there are spawns in the bar!!

### CODE REVIEW

**Comment by ghost** [comment]
- Added lattices to escape shuttle area so the 'shape' of the shuttle is easily seen and traversing the perimeter of it is a lot easier.
- Expanded the space part of arrivals expansion a bit
- Added lattices to the outside of the singularity engine area so you can safely hop from one side to the other without being pulled into it (nuke ops don't fuck this up now please)
- Added spot below arrivals for a new type of admin shuttle that hasn't been implemented yet (soon, death squad, soon.)

These are mostly updates box on sybil has done that I've transferred over here for the sake of some consistency between box and metastation.

**Comment by ghost** [comment]
- Lowered the amount of plants in perma
- Redid a few descriptions
- Redid docking bay lattices a bit (One day we will get big bright blinking lights to put on these plating tiles like on the lobby screen)
  ss 2014-06-25 at 02 00 47

Pic of engine safety lattices:
ss 2014-06-25 at 02 01 30

**Comment by ghost** [comment]
This is merge ready and I don't wanna touch it anymore.

**Comment by ghost** [comment]
@Metacide

I updated the map again for the codebase and THIS should be the last one I'll do for now since I fixed all the erros with my proviosu update.

**Comment by Iamgoofball** [comment]
:-1: no drunk in space spawn

**Pull request merged**
