### PR TITLE
Moon Outpost 19 [Away Mission]

### PR DESCRIPTION
**Pull request by WJohn**
The first actually GOOD and DETAILED away mission ever made.

Does not have huge amounts of loot for you to find. A usually empty shotgun (rarely with one beanbag shell), a not immensely hazardous atmosphere that can be survived with internals and a coat (finally a use for them), huge amounts of var editing fun for the lockers and air alarms and APCs etc. Immense amounts of fluff text has been written for it, too!

And hey, it's not a mob killing fest!

Some very slightly outdated pics:
http://i.imgur.com/0KCZgiM.png
http://i.imgur.com/nAyxZIk.png

### CODE REVIEW

**Comment by theOperand** [comment]
Is this compatible with tg?

**Comment by WJohn** [comment]
I'll need to remove some of the equipment from the kitchen, but otherwise I don't see anything too wrong with it. There are no code changes in this whatsoever.

**Comment by RemieRichards** [comment]
@WJohn Did you use any of Goof's Away mission Areas? I don't believe /tg/ have those.

**Comment by WJohn** [comment]
Ah yes I did use those areas. I suppose I'd have to replace them with some other areas used in other away missions and hope those use power.

**Comment by ghost** [comment]
Meh

**Comment by WJohn** [comment]
You know this has been merge ready for a while now. You can add it any time.

**Comment by WJohn** [comment]
Thank you <3

**Comment by ike709** [comment]
Finally a fun away mission.

**Comment by ghost** [comment]
You haven't even tried it.

**Comment by Iamgoofball** [comment]
how do you know he didn't load it up locally?

**Comment by ike709** [comment]
@paprka 

> how do you know he didn't load it up locally?

**Pull request merged**
