### PR TITLE
More gang weapon nerfy things

### PR DESCRIPTION
**Pull request by ghost**
- Glock removed from protolathe (If you got the materials for it you're better off building a 1911 anyway nigga)
- Metal bat removed (Metal is easy as fuck to find and mass producing bats is dumb)
- All weapons/weapon parts made from sheets now have build times so you can't shit out 50 baseball bats
- Some stuff moved around
- Pair of 15 brute _s-self defense_ blingy brass knuckles added to mining equipment locker as a reward for doing your job well! After all, miners are gonna need a decent weapon when they come back to that traitor/cult/rev infested station.

I URGE you to check out my code notes when it comes to the weapon nerfs, it'll help explain the thought/balancing process behind the nerfing.

### CODE REVIEW

**Comment by ghost** [comment]
No worries on the travis failing there's some things I forgot to test.

**Comment by ghost** [comment]
I'll also be fixing the wood plank icon missing in a sec

Edit: Done

**Comment by Atskadan** [comment]
:+1: people having tons of bats is dumb
ultimately i'd like to see all the gang weapons require actual recipes using razharaz' table crafting

**Comment by ghost** [comment]
hell yeah, that'd make the glock less easy to make.

**Comment by ghost** [comment]
15 is as much as a null rod, butcher's cleaver, pickaxe... that should really speak for itself. I also buffed it to go along with this, it doesn't take as much plasteel to make the handle now. 15 is PLENTY to justify making it, you can shit all over people using a 15 brute weapon.

I'll readd the metal bat as a weapon.

Also @ "never straight up remove items": Tell that to cheri removing fucking stun gloves outright he was so bottom bothered by them. I wanted to use those for a traitor item but NOOOOO gotta outright delete cool weapons.

**Comment by Iamgoofball** [comment]
@paprka stun glove removal has almost nothing to do with this 

why are you bringing it up

besides, I've got plans for the gloves.

**Comment by ghost** [comment]
Goofball please learn to read m8.

**Comment by ghost** [comment]
What do you think I'm trying to prevent here HG? Oh wait, it's too late for prevention, because this stuff gets merged without anyone talking about the grander scheme of balance on the forums or asking anyone who knows their shit. When I originally saw the PR for these weapons, I didn't even bother to look at the damages of the weapons because I thought the people adding them knew the game well enough to know that **there is a scarcity of 15+ brute weapons for a reason.** 

Hopefully a lesson will have been learned as we wait another week for an update to rebalance them. Live testing is fun and all but I'm getting awfully tired of stuff getting added and then having to wait a week of them being on the server for a new update to fix them because the person who added them didn't test it/fix it on the spot. _It's not a huge issue for a lot of things_, but new weapons is DEFINITELY on the list of things you need to consider very patiently.

**Comment by ghost** [comment]
Foreverial salty HG, permanently bitter about his horrible stun and move speed balances that nobody liked. I love the irony in that.

I've already taken all those things into account, this PR is evidence I know what I'm doing with balancing, especially after we've live tested these things and those issues have come up with people mass producing stuff. I'm honestly not going super mean mode and hating on the update because the gun building is actually cool as fuck and the switchblades are also a pretty cool item and during rev I've seen them be an incredibly cool tool that revs use to fight 50 e-gun security in a balanced way and it's been really really fun to see. Rev is hardly ever balanced on arty because on lowpop not everyone signs up as all the heads so that's an issue with rev itself but we've still had some decent rounds come out of this.

I think with my balance changes, while it makes it slightly easier to make switchblades(10 plasteel is a lot, even for balance), it doesn't put much value in them because while switchblades are a 7-hit crit, like toolboxes, there's plenty of other items around the station that have a slightly worse damage like extinguishers or hatchets BUT you won't get those taken away by security because they're provided by NT for crewmembers to use(most of the time sec won't anyway, if you haven't hurt people with them.. yet). Gimmicky greyshirt vigilante gangs still have their robust switchblades, which are just as good as the butcher's cleaver but not as rare or hard to make. (I think you can actually just hack a kitchen vender to get a cleaver anyway which is way easier than getting a switchblade)

There's even weapons you can make that are BETTER than the switchblade, like the spear when it's wielded, but that doesn't fit in your backpack/pocket. Ultra robust greyshits are probably better off using those still anyway. In any case, I don't want to make 15 brute weapons prolific as much as the next guy but plasteel is hard enough to find to make it justify the damage.

**Comment by Atskadan** [comment]
Honestly "improve not remove" is a flawed mentality. Not everything is worth keeping, and just because it existed once doesn't mean it wasn't a bad idea to begin with. There are times when it is better to improve, and not remove, but simply keeping items that only contribute as clutter just because of "improve not remove" is a bad idea. 

I bitched at you, @dannno, about the damages, because you <i>told me the items would be for map makers only</i>. 

> for mappers I guess

Giving everyone high damage weapons for virtually no cost was a horrible idea in practice. 
A switch-blade, which you can make a pretty-much-infinite amount of, (if miners actually made plasteel) doing as much damage as a fire axe used to do, which there are only 3 of on the station, is absolutely ridiculous. A concealable weapon that you can make out of raw materials in large quantities should <i>never</i> be better than the unconcealable, rare counterpart which much be wielded with 2 hands to use effectively. Traitor items get a pass, since they're meant to be good.

I do take the blame for causing the issues with the gang weapons, as I hadn't really taken a full look at all of the changes before pulling it. However, we cannot dismiss the fact that there ARE major issues with the way they were implemented that need to be changed. Consider that welders are a commodity and do 15 damage, yet they require fuel. Rarer weapons such as the butcher knife do 15 as well. 15 damage should not be a commodity that comes without some price. Weapons like that should be either rare, harder to make, or come with a downside, like needing 2 hands. Many of the gang weapons are pretty much direct upgrades from rarer items without the cost that finding or making these items have.

**Comment by ghost** [comment]
Also you can shit out two butcher's cleavers from a hacked silverware machine which are better than switchblades (something i used to do when there wasn't a chef quite often) so I don't think the switchblades will be too riddick anymore.

@hornygranny Taking poll results as HAHA MY CHANGES WON is completely fucking stupid because every single one of those people who voted for 'slower speed' are actually voting for speed FASTER than your changes, just slower than NT is currently. Same goes for stuns. You can go back to being irrelevant again instead of trying to 'refocus' the combat away from stuns because you're bad and cocking up this branch because you're bitter that the FIRST thing NT reverted from /tg/ was your lazy ass rebalancing.

**Comment by Iamgoofball** [comment]
@paprka you need to _calm the fuck down_

like, seriously

go out and take a walk

get some fresh air

do those things I tell you people to do every single fucking time this 4chan community gets pissy and starts throwing temper tantrums like babies, but you never end up doing

**Comment by ghost** [comment]
can this get merged already

**Pull request merged**
