### PR TITLE
[dont merge] Enables Random AI laws and puts a few lawsets into the list of potential random lawsets.

### PR DESCRIPTION
**Pull request by Iamgoofball**
Since the AI poll ended with a draw, I figured we should follow the teachings of soft and crunchy taco commericals and allow any lawset to be rolled, instead of just doing 1 lawset to rule them all.

Supplementary video:
http://www.youtube.com/watch?v=vqgSO8_cRio

### CODE REVIEW

**Comment by Atskadan** [comment]
it's not waiting til the last minute when i didn't even know you were going to do this
plus the thread we already had didn't have a lot of indepth discussion over all the nuances of the issues in baylaws
i personally like baylaws but they need a lot of policy writeup before they can be used, and i do not agree with your addition of "laws are no longer prioritized at all," especially for ion and uploaded laws

**Comment by Neerti** [comment]
Don't forget a poll on forums.

**Comment by Iamgoofball** [comment]
miggles is handling that as I'm heavily biased towards "fuck asimov"

**Comment by ghost** [comment]
fuck asimov

**Comment by Tomeno** [comment]
fuck baylaws

**Comment by ghost** [comment]
fuck you

i'm your prom date you ugly sack of shit

**Comment by Iamgoofball** [comment]
so uh, how about counting those poll results sometime?

**Comment by Atskadan** [comment]
nah

**Comment by Iamgoofball** [comment]
i'll do it myself then

**Comment by Iamgoofball** [comment]
https://github.com/NTStation/NTstation13/pull/876

**Pull request closed without merging**
