### PR TITLE
Adds atmos coats to atmos wardrobe lockers and moved pinpointer to HoS office

### PR DESCRIPTION
**Pull request by ghost**
Not exactly sure why the HoS never had a pinpointer when it's practically his job to babysit the cap.

Also atmosia coats yeah!!!

### CODE REVIEW

**Comment by GunHog** [comment]
Remove the Captain's if you are giving it to the HoS. There should only be one of these so that the strategy of spacing the pinpointer is not made two times harder for Stealth Ops and Malfunctioning cyborgs.

**Comment by ghost** [comment]
No PR is safe from gun hog's keen AI regular eye

**Comment by ghost** [comment]
The cap should be aware of the recent change since the note is literally right next to the disk so here's hoping people don't faff about it suddenly being missing!

**Comment by Atskadan** [comment]
yes please i was so cold without my atmos coat ;n;

**Pull request merged**
