### PR TITLE
[WIP][Do not merge!] New plants

### PR DESCRIPTION
**Pull request by Tokiko1**
*Adds a new plant: The singulo potato. You can crush it in your hand to create a singularityhammer vortex effect that will pull nearby items and people to you! Range and stuntime is dependent on potency. Stun is capped at 4 ticks. Note that this does no damage at all.

TODO: Sprites!

*Adds a new plant: The spiderplant. The spiderplant mutates from eggplants and yields spiderpods. Spiderpods have 3 uses:
1. You can grind them to get poisons.
2. You can cut them into pieces to get spidermeat for cooking. The amount of meat depends on the potency of the pod. The meat also includes all the reagents that were in the pod when cut!
3. You can pry them open to possibly release a spiderling. The chance of it working is pretty low and even at potency 100 it is only 60% so you better work hard if you want to fill the station with spiders!

Spiderling spawning and attempted spawning with the pods is logged for admins too.

TODO: Sprites!

*Walking mushrooms can now go on a rampage! Feed them killer tomatoes(placeholder for now) to make them fight every creature, not just other mushrooms! Do note that they will still fight each other to death so using more than 1 mushroom for a murder spree is greatly discouraged. Rampaging mushrooms won't attempt to devour other mushrooms and can't level up anymore.

Todo: Expand walking mushrooms a bit, balance their values a bit more. Maybe a frightening custom sprite depending on their level?

*Makes blood tomatoes spawn gibs on squashing.

TODO: Make it dependent on potency.

I would greatly appreciate spriting help with this. All sprites are currently placeholders...

### CODE REVIEW

**Comment by ike709** [comment]
I think the singulo potato should be logged too, since it does knock down, pulls people toward you, and stuns them briefly. This can lead to all kinds of bad things, and I can provide examples. But also buff the stun time slightly as a tradeoff since 4 ticks isn't much.

**Comment by Tokiko1** [comment]
7 tiles at 100 potency. Too big?

**Comment by ike709** [comment]
No, but see updated comment.

**Comment by Lumipharon** [comment]
sounds quite strong, if you couple it with a polysmoke nade/mini bomb. Pull them all in,throw a cooked nade on em.

**Comment by ExplosiveCrate** [comment]
If you cook the bomb, you're either going to get caught in the blast or are going to give them enough time to run away because the stun time is so small.

**Comment by Tokiko1** [comment]
Don't underestimate the stuntime. It's enough to shoot someone with a stunning weapon or whack them with a deathnettle. I might even reduce it further to 2 ticks.

Also added logging for the singulo potato. Allura is kindly working on some sprites for these plants.

**Comment by RemieRichards** [comment]
I'm glad you logged the Spiderlings, that's good thinking.

**Comment by Tokiko1** [comment]
Added a new feature: Walking mushrooms attacking mobs other than mushrooms if you feed them a certain item.

**Comment by ike709** [comment]
How powerful are the rampaging mushrooms?

**Comment by Tokiko1** [comment]
Depends on how much far you level them up and how good the plant stats were when you planted them. Currently, their stats are capped at 30-50 damage and 200 health. 

I may move the mushroom update to its own PR. It's very fun to code this and I'd like to keep adding things like special abilities, unique mushroom types and different forms which will probably take a bit of work. The other plants are completely functional and only need sprites now.

**Comment by Lumipharon** [comment]
Speaking of killer tomatoes, could you actually make them like, killer? Make it based on potency, both their damage and aggressiveness (siht potency they don't attack anything, mid potency they retaliate, high potency they attack everything). botanists need more cool shit for tators.

**Comment by Tokiko1** [comment]
For some reason, the way I attempt to log the spiderpod usage does not work. No error message but no logs either. Can anyone help me out with that?

Edit: Nevermind. I figured it out.

**Comment by Tokiko1** [comment]
Ehh, messed stuff up.

**Pull request closed without merging**
