### PR TITLE
[Small Map Edit] Bot fixes + Roboticist access increase!

### PR DESCRIPTION
**Pull request by GunHog**
- Fixed an issue where unlocked bots continued to refuse On/Off command
  to unauthorized users.
- Centralized AI bot calling code a bit for the bots.
- Changed emagging/hacking logic such that hacking a bot still works if
  the interface is emagged to an unlocked state, but the bot itself is
  not.
- Fixed an issue where a bot that has been unlocked by an emag by not
  actually emagged would show as emagged to the silicons.
- Floorbots no longer attempt to build in space or shuttle docking
  areas.
- Floorbots will now make tiles from metal sheets of any amount, not
  only single sheets. It will convert the metal into tiles only one sheet
  at a time
- Navigation beacons now use the sexier black UI. Also added a span class for the honks.
- Roboticists now have access to navigation beacons, floorbots,
  cleanbots, and medibots.

_If you found any other bugs with Botcall, now is a VERY good time to post them!_

### CODE REVIEW

**Comment by Tokiko1** [comment]
What about Scrubs MD and the other cleanbot in the security maint area, can those be turned on by security/medbay personal yet? Because right now they can't which is weird. Maybe have them start out unlocked?

**Comment by GunHog** [comment]
I edited their instances on the map - Sec now has access to Sweepsky, and Medical types can control Scrubs. Thanks for pointing them out!

**Comment by GunHog** [comment]
@NTStation13Admin  this should be ready unless anyone has anything else to point out, or you have concerns!

**Comment by RemieRichards** [comment]
@GunHog Wrong account to @ you should @NTStation/contributors

**Comment by GunHog** [comment]
Oh, okay, thank you, RR!

**Comment by Iamgoofball** [comment]
> implying miggles actually looks at the github anymore

pls

**Pull request merged**
