### PR TITLE
Cyborgs, securitrons, and ED-209s now have zipties instead of handcuffs.

### PR DESCRIPTION
**Pull request by ghost**
They take less time (cable cuff time) to break out of and are disposable, as in they break once you take them off.

This should solve the free cuff machine beepskies and cyborgs having to stare at cuffs on the ground or drag them away after they uncuff someone.

### CODE REVIEW

**Comment by MrSnapwalk** [comment]
There was some discussion about giving sec officers stackable zip-ties as an alternative to handcuffs. Could you take a look at doing something like that?

**Comment by ghost** [comment]
That was my idea. I already did take a look at doing it, and unfortunately it'll take a bit more hacky code i'm not capable of doing atm. It's kind of complicated but I'm sure someone else will figure it out eventually, this is just a stand-in for the things on the station that really need them, beepskies and cyborgs.

**Comment by ike709** [comment]
But how are we supposed to get free handcuffs?! You monster!

**Comment by ghost** [comment]
:)

**Comment by ghost** [comment]
BY THE WAY RR HELPED ME DO MOST OF THIS CODE :+1:

**Comment by Atskadan** [comment]
thanks remie

**Pull request merged**
