### PR TITLE
Paintball

### PR DESCRIPTION
**Pull request by JStheguy**
-Adds paintball guns and paintballs (With splatter effects if they don't hit someone.)
-Adds paintball masks and cheap sunglasses that don't block flashes n shit.
-Adds the above to the lasertag equipment lockers.
ss13bandana

### CODE REVIEW

**Comment by Iamgoofball** [comment]
> paintballs aren't made of chemicals

:-1: until we can make chemicals out of paintballs

**Comment by ghost** [comment]
can we inject chemicals into paintballs like eggs

**Comment by Atskadan** [comment]
cant automerge btw

**Comment by ghost** [comment]
BECAUSE I UPDATED GUN.DMI

HAHA JS MY BINARY FILE UPDATES STRIKE AGAIN

**Comment by Atskadan** [comment]
@JStheguy

**Comment by Atskadan** [comment]
@jstheguy still not mergeable

**Comment by JStheguy** [comment]
No shit it's been 10 days since I last updated.

**Comment by Atskadan** [comment]
that means you should fix it

**Comment by JStheguy** [comment]
Thing is where is the problem?

**Comment by Atskadan** [comment]
your files are not up to date
thus there are conflicts
pull the most recent changes and tell me which ones are conflicted

**Comment by Atskadan** [comment]
pls

**Pull request closed without merging**
