### PR TITLE
[WIP] Syndicate Operative additions

### PR DESCRIPTION
**Pull request by ghost**
http://tgstation13.org/phpBB/viewtopic.php?f=14&t=205
- Changes the Stechkin silencer to a 'universal' syndicate silencer for all small arms. This currently only includes the Stech and C20r SMG.
- Adds the 30-round spess AK, a less clunky but lower ammo 7.62 rifle, manufacturing title "CB-47"
- Adds the mag-fed semi-automatic syndicate operative shotgun, manufacturing title "S-12p"
- Adds three 8-round shotgun magazine types: Buckshot, Stun Slug, and 'Dragon's Breath' (Incendiary)
- sAK and S-12 have identical TC prices, offering a decent variety in loadout selection and notably a replacement for the 'necessity e-guns' on the syndie shuttle.
- Semi-automatic shotgun available in the protolathe with enough syndicate reverse-engineering (level 5)
  [Buckshot and stun magazines included]

 
 

Robrichards: Silencer code redux
Nienhaus: Main spriting
Pandarsenic: Magazine sprites
MrSnapwalk: Inhand sprites

### CODE REVIEW

**Comment by ghost** [comment]
oooooooperative ooooooooooperating oooooooooooooperations

**Comment by Atskadan** [comment]
cb-47 / sak is a dumb name

**Comment by RemieRichards** [comment]
Make Silencers a Proc instead of duplicate code

Edit: I've made a PR on your Branch @paprka 
Edit2 : https://github.com/paprka/NTstation13/pull/1 I did it myself, it contains the Request I made and all the stuff you need to be up to master (it'll look like a lot (over 100 changes) but that list will disappear once merged into the PR)

Edit3: it's all done.

**Comment by GunHog** [comment]
MORE REVERSE ENGINEERING

**Comment by ghost** [comment]
Based rob fixing everything

Miggles is a dumb name too don't be a cheeki breeki

**Comment by ghost** [comment]
Incendiary does less damage and the magazines have 20 rounds rather than 30 for balance. They are also 1tc more expensive.

**Comment by ghost** [comment]
Stun slugs are now the default magazine type on the auto shotty. I may revert this change in the future, because of the protolathe. This change is there for the shotguns to replace the e-guns as the stun alternative.

**Comment by Atskadan** [comment]
OH MY GOD WHY ALL THESE COMMITS HRGAHGAAAAAAA

**Comment by RemieRichards** [comment]
That's what working in an old/behind branch when you're in such a rapidly evolving codebase nets you.

**Comment by ghost** [comment]
blame git, git hates trying to update

i can remake this if you really want

**Comment by ghost** [comment]
Going to clean this up and remake due to all the updates.

**Pull request closed without merging**
