### PR TITLE
Adds crew transfer shuttle voting and auto vote creation

### PR DESCRIPTION
**Pull request by ghost**
Paprika the savior of lowpop.

~~This is half-assed for now and currently does not have any special text to differentiate transfer shuttles from normal emergency shuttles, that will come later (when me or someone else figures it out and ports it).~~ DONE

Currently:
- A vote is called for a transfer shuttle call 2 hours into the round and every subsequent hour
- It is affected by things like malf, blob, rev, etc because it basically just triggers ~~an emergency shuttle~~ a modified emergency shuttle call. If there are limits on the shuttle call (too early in the round, delta, red alert refueling, etc) it will not call the transfer shuttle.

Bay's alarms are included for all vote types, including custom admin votes, so enjoy that.

Admins can call votes for it, so can other people if admins enable it, but it's disallowed by default.

### CODE REVIEW

**Comment by ghost** [comment]
Another feature port in the bag, back to webbing!

**Comment by Iamgoofball** [comment]
the vote sound bs12 uses is horrible, hurts ears, and you can't turn it down without muting the game

please don't use BS12's vote alarm, use a different one

**Comment by ghost** [comment]
It's supposed to get your attention.

**Comment by GunHog** [comment]
I wish it could be IC somehow.

**Comment by ghost** [comment]
It's semi-IC. But the point of it not being on the consoles is so they aren't fought over IC, it's meant to be just a 'okay, 2 hours of this shit, nobody's making a move, time to reset the round.'

**Comment by Iamgoofball** [comment]
My ear drums don't agree that loud as fuck is required for getting attention.

**Comment by Atskadan** [comment]
There are certainly better sounds already in the game that can be used for this.

**Comment by Dorsisdwarf** [comment]
alarm.ogg gets people's attention like nothing else in the game.

**Comment by ghost** [comment]
Start pointing some out or providing new sounds, then.

**Comment by ghost** [comment]
Alarm changed to a shorter version of 'bloblarm' which is easier on the ears. It also no longer plays during custom votes (created by admins in other words).

**Comment by ghost** [comment]
**NOTE TO WHOEVER MERGES THIS:**

PLEASE PM scaredy and tell him to add:

```
## autovote initial delay (deciseconds) before first automatic transfer vote call (default 120 minutes)
VOTE_AUTOTRANSFER_INITIAL 72000

## autovote delay (deciseconds) before sequential automatic transfer votes are called (default 60 minutes)
Vote_AUTOTRANSFER_INTERVAL 36000
```

To HIS VERSION of the config txt. This is REQUIRED in order for this to work properly.

**Comment by Atskadan** [comment]
ready to merge?

**Comment by ghost** [comment]
Yes but you must alert scaredy to add that thing to his config I do not want that left out

**Comment by Atskadan** [comment]
done

**Pull request merged**
