### PR TITLE
[Ready] /tg/ Merge May 20

### PR DESCRIPTION
**Pull request by Atskadan**
Needs serious review and checking for issues and unwanted changes.

### CODE REVIEW

**Comment by Neerti** [comment]
You got GPL'd.

**Comment by RemieRichards** [comment]
tfw travis.

**Comment by Atskadan** [comment]
its almost as if changing 301 files may lead to compile errors :exclamation:

**Comment by optimumtact** [comment]
code/datums/helper_datums/getrev.dm:9:error: missing left-hand argument to <<. It's ogre!

**Comment by Atskadan** [comment]
I've already most of the errors.
I've only got a few more compile issues to fix, (around 5) but I was waiting til the weekend to finish the job.

**Comment by ghost** [comment]
thank you for doing this

**Comment by ghost** [comment]
Yes. Thank you very much Miggggles

**Comment by Atskadan** [comment]
Additionally, there are some files in this PR that I don't feel should be there, (contributing.md and box2.1.3 for example) but to spare myself the pain of reverting everything and recommitting it sans a few files, I'll make a second PR after this one which nix them.

**Comment by Atskadan** [comment]
travis you nignog

**Comment by Atskadan** [comment]
OK IT'S READY

**Comment by ghost** [comment]
HYPE FOR TEARS

**Comment by Rolan7** [comment]
I'm really glad this happened, good job!

**Pull request merged**
