### PR TITLE
/tg/ merge 2: electric boogaloo [Ready]

### PR DESCRIPTION
**Pull request by Petethegoat**
Another merge, mainly to grab qdel fixes, Aran's click cooldown removal (FUCK YES), and fleure's dept sec access fix.

### CODE REVIEW

**Comment by Atskadan** [comment]
Nice. Tell me when it's ready.

**Comment by Atskadan** [comment]
Please add https://github.com/tgstation/-tg-station/pull/3234, it's pretty important.

**Comment by Petethegoat** [comment]
Will do that as soon as it's merged. Thanks for the heads up.

**Comment by Atskadan** [comment]
You wanna do that in another PR or wait for it and put it in this one?

**Comment by Petethegoat** [comment]
We can wait.

**Comment by Atskadan** [comment]
That ~important pull~ was pulled.
Make sure you don't also merge the April Fools' day stuff before it's reverted.

**Comment by Iamgoofball** [comment]
we can't automagically merge this pull request anyways

**Comment by Atskadan** [comment]
So? It's not meant to be pulled yet.

**Comment by Iamgoofball** [comment]
good point

**Comment by Petethegoat** [comment]
Updoot.
Manually reverted https://github.com/tgstation/-tg-station/pull/3230.
Was there anything else that needed to be addressed?

**Comment by Atskadan** [comment]
hmmm, nope. 
looks good

**Comment by Petethegoat** [comment]
join irc u

**Pull request merged**
