### PR TITLE
Changelog for organic_effects

### PR DESCRIPTION
**Pull request by RemieRichards**
Changelog foools.

### CODE REVIEW

**Comment by RemieRichards** [comment]
Self merging woo so against the rules

**Comment by Atskadan** [comment]
demaintainerd

**Comment by RemieRichards** [comment]
@Atskadan :P

**Comment by Atskadan** [comment]
you think this is a game

**Comment by RemieRichards** [comment]
@Atskadan  I think this is a game coded in Dream Maker a small language by a guy named Tom.

Honk.

**Pull request merged**
