### PR TITLE
Drone Updates

### PR DESCRIPTION
**Pull request by RemieRichards**
- Sprites switched on East/West
- Drones can now be picked up by humans
- Drones can now choose to repair a dead drone instead of eating it (free repairs atm, no resource system yet)
- Drone production is Mechfab only now and has correct costs and timing
- Drones can no longer pickup anything that is technically a "gun" including wizard staves - Miggles :/

(The dme is just cleaning some blank lines out)

### CODE REVIEW

**Comment by ike709** [comment]
Rip drone mass suicide with the ion rifle.

**Comment by JJRcop** [comment]
Can you put `real_name = name` after `name = "Drone ([rand(100,999)])"` in `New()`? It will solve the problem of all ghosts being just "drone", and they will instead also have their number after them.

**Comment by RemieRichards** [comment]
Thanks @JJRcop I always forget real_name, I keep thinking it's tied to DNA when it's only USED in DNA.

**Comment by Niknakflak** [comment]
Is there anything involving storage/materials yet or is that coming later or not at all?

**Comment by RemieRichards** [comment]
@Niknakflak I made a system for it. It didn't work, so I scrapped it and applied the changes that did.
Of my work Yesterday only Resources didn't make it in.

They'll get there. at some point.

**Comment by MrSnapwalk** [comment]
Please add some way to stop dragging an item. It's so annoying to have to go through vents or have another drone pull you in order to stop pulling.

**Comment by RemieRichards** [comment]
@MrSnapwalk It's Del. the Del key regardless of Hotkey mode or not. It'll stop pulling. So I believe will ctrl clicking the object again. (if it's not del it's one of the 6 keys, Insert,Home,PageUp,Del,End,PageDown)

but yes, I'll add the hud object for stopping pulling to Drones at some point.

**Comment by ike709** [comment]
It is the delete key.

**Comment by RemieRichards** [comment]
Self merging because of the Fixes and lack of the other maintainers

**Comment by Atskadan** [comment]
> Drones can no longer pickup anything that is technically a "gun" including wizard staves - Miggles :/

@RemieRichards why am i mentioned here?

**Comment by RemieRichards** [comment]
@Atskadan 

> dron chat pls
> exclude obj/weapon/gun etc 
> make the drone hive object for the map even if you dont put it in yourself
> on that last point, the lack of tools, is that intended?

First place I remembered seeing the request for no guns.

**Comment by Atskadan** [comment]
ok ok
i think someone else mentioned it and i was just repeating them but im not sure and it doesnt really matter

**Pull request merged**
