### PR TITLE
Merge with /tg/ [Ready]

### PR DESCRIPTION
**Pull request by Petethegoat**
This will revert us back to /tg/ mining values, but it's much easier to address that after the merge.
I haven't noticed any other issues.

Unrelated changes:
Fixed energy gun and taser inhands (east/west hands were reversed)
Fixed hivelord remains not showing up.
Removed superfluous ID card colouring on data cards and emags.
Flashlights no longer have a separate indicator that they're turned on, but otherwise keep the updated sprite.

### CODE REVIEW

**Comment by StarToad** [comment]
This'll merge the speed nerf and stun nerf. You might wanna gut those bits from it before it gets added in. Also merging in the metastation updates will cause issues. Bluebay will also cause compile issues, as we saw a few days ago.

**Comment by Petethegoat** [comment]
It compiles fine, and doesn't include the speed or stun nerfs.
I kept our version of metastation as I don't know what changes were made.

**Comment by Iamgoofball** [comment]
you missed the Mime Mech pr

**Comment by Atskadan** [comment]
Were any changes made to Metastation? I didn't think there were. Compile errors should have been fixed as well.

**Comment by Petethegoat** [comment]
I left metastation as it was, so that's not been updated to the /tg/ version. I've only tested compiling on box so far.

**Comment by Atskadan** [comment]
Please see about updating metastation and adding the mime mechs.
A PR right after this which returns the mining values to the NT values would also be ideal.

**Comment by Petethegoat** [comment]
Metastation does not compile right now. Working on this.

**Comment by Atskadan** [comment]
That's odd.
Any idea why that's an issue?

**Comment by Petethegoat** [comment]
It just wasn't updated when some stuff was reverted earlier. Should work fine now.

**Comment by Petethegoat** [comment]
Also, this includes a few extra /tg/ commits, most notably Incoming's second wave of magic mania stuff.

**Comment by Atskadan** [comment]
IT IS LAW

**Pull request merged**
