### PR TITLE
Rebalance of space suit/rig helmets.

### PR DESCRIPTION
**Pull request by ghost**
**Normal space suit helmets no longer conceal your identity nor protect against flashes or welding.**
Use gas masks or sunglasses instead.
**RIG helmets conceal identity and have flash/welding protection depending on what they're used for.**
**Engineering/Advanced RIG helmet have welding protection, the atmos helmet does not.**
Reason being is because the atmos hardsuit is completely fireproof and this can be incredibly valuable. ENGINEERS are supposed to weld in a vacuum, not atmos techs. Atmos techs have welding helmets for non-vacuum welding.
**Combat RIGs (syndicate blood-red, security) and syndie space suits have basic flash protection now, but not welding protection. They are also identity-concealing.**
- Basic gar glasses you can obtain from autodrobes, the orange ones, are no longer flash-protected like sunglasses. The orange captain gars are still flash protected however.
- Meson GARs have the proper attack force and throw force now.
- Death squad space suit properly airtight and biohazard protected.
- Some tweaks to themed space suits like pirate and santa.
- Space helmet sprite is slightly transparent, you can slightly make out a face of who's inside because immersion.
- Atmos tech helmet sprite tweaked to be more revealing than the engineer and advanced helmet because it lacks welding shielding now.

### CODE REVIEW

**Comment by GunHog** [comment]
Why are you doing this? Do we TRULY need nerfs here?

**Comment by ghost** [comment]
Do you really think a bunch of greyshirts raiding eva to steal space helmets so they can be flash protected and weld into whatever walls they want is a legitimate good thing

**Comment by ACCount12** [comment]
Another pointless nerf? IN OUR CODEBASE? 
NO WAY! :-1:

**Comment by Niknakflak** [comment]
Atmos hard suit helmet should also get welding protection.  They fix the disposals pipes and sometimes that is in space.  Not to mention, atmos techs sometimes act as station engineer if there are none.  Useless nerf, I never see people run around with EVA space helmets.

**Comment by GunHog** [comment]
Paprika, I propose a new way to go about this. <b>Address the behavior directly!</b> Someone came up with the idea to have the helmets be collapsible into the RIG itself, akin to how they work in Dead Space 2 and 3! Just do that instead!

You must be wearing the suit in order to activate the helmet. This fixes the act of wearing a helmet without a suit, and avoids having to nerf things in an attempt to obtain the same result.

Furthermore, it somewhat discourages the act of carrying the suit in-hand to avoid the slowdown penalty.

**Comment by Atskadan** [comment]
what gunhog said yo

**Comment by ghost** [comment]
Someone needs to make the normal space suit look like the EVA rig from dead space 3 then.

Also I'm literally not even going to bother coding that, it's an entire rework of a lot of code, but until it is this is the only way to nerf the retarded legions of grey tiders wearing space helmets for flash and identity protection, which doesn't even make sense.

Also I could just add slowdown to the helmets themselves lol.

**Comment by Atskadan** [comment]
also atmos helmets need welding

**Comment by ghost** [comment]
But that makes them a direct upgrade from engineering helmets. I've already stated why they don't have it and I need an actual counter argument.

**Comment by ACCount12** [comment]
Why don't remove (or reduce to a simple very dark overlay) welding helmet's tint overlay instead and put some welding helmets in tool sotrage?

**Comment by ghost** [comment]
I wanted to make it so rig helmets naturally had a bit of a peripheral reduction so you couldn't wear them 24/7 and not have any detriment but i'm not sure how the code for that works. I'd be willing to make them have flash protection again. There has to be SOME kind of negative part of space/rig helmets...

**Comment by ike709** [comment]
I'm glad normal space helmets no longer protect flashing, but if you want to remove welding protection then you should do what ACCount12 said and add welding helmets to tool storage. Also, atmos helmets should have welding protection since its basically an engineering helmet...

**Comment by ACCount12** [comment]
RIG helmets limiting vision is pointless. 2D spessman can see 360 from welded wrapped locker, even if locker is stuffed into Ripley's cargo storage. Why some shitty helmet must limit his vision?

Having RIG helmets with welder protection but without flash protection is impossible with current code. Flashes are at eye protection level 1, welders are on 2.

**Comment by ghost** [comment]
'Also, atmos helmets should have welding protection since its basically an engineering helmet...'

Except the part where it's completely fireproof?

**Comment by ike709** [comment]
Yes, exactly. You act like Atmos techs never do the engineers' jobs for them.

**Comment by ghost** [comment]
Use a welding helmet then.

**Comment by ACCount12** [comment]
Use a "Close pull request" button then. This is nt, not tg where you can nerf everything that personally YOU hate.

**Comment by Atskadan** [comment]
"direct upgrade" lol 
if someone wants to steal the atmos hardsuit helmet and use it instead of a normal helmet uh good for them 
i totally expect people will do this because of <i>fire protection</i> 
when fire suits exist
and fire extinguishes itself in space
meaning theres never going to be a specific need for fire protected engineers in space unless they really just want that powergamer boost

**Comment by ghost** [comment]
You can't use a fire suit in a plasma fire alone most of the time, there's typically pressure involved. Also, try breaking into an AI core with a plasma flood inside without the advanced/atmos rig, it might be situational but it's still a direct counter to an extremely common tactic.

I have a better idea to counter people running around with rigsuit helmets on, as long as EA doesn't sue me for using gun hog's dead space rig helmets idea.

I still think EVA space suit helmets shouldn't have flash or identity protection, but I'll address that when I finish coding the other thing.

**Pull request closed without merging**
