### PR TITLE
some medbay stuff and clothes

### PR DESCRIPTION
**Pull request by Tokiko1**
Clothing stuff:
shirts and coat
*Adds a new first-responder winter coat to the medbay clothing locker which has the same colors as the first responder jacket. For when you need to EMT work near breaches!
*Removes the belt looking thing from the nurse suit so it looks a bit nicer.
*Finally fixes the "missing sprite" bug that happened when you tried to button up a regular labcoat.
*Adds another, seperate version of the white undershirt and black undershirt that doesn't look like it has been ripped apart. They're simply called White Shirt 2 and Black Shirt 2 in the list.

Item stuff:
*Adds 5 bicaridine and 5 kelotane syringes to the medivend. This was part of my autoinjectors update but I still want this in so doctors are actually encouraged to choose between syringes, pills or bruisepacks/ointments when deciding the contents of their medibelt.
*Adds one more spaceacilin syringe to the medivend for a total of 5, just so it's more consistant with the above items.
*Adds another medhud to the medical lockers. 2 medhuds are simply not enough for the entire medbay. I've seen quite a few people complain about this recently. Sure, the CMO has some of them but the CMO actually existing and then bothering to give these out is too rare.

### CODE REVIEW

**Comment by RemieRichards** [comment]
If it's ready I'll merge it at some point today, just ping me.

**Comment by Tokiko1** [comment]
Alright, this is ready. I'm not sure how to ping though!

**Comment by Niknakflak** [comment]
NON RIPPED UNDERSHIRTS WOOO TOKIKO FOR NEW BEST CODER

**Comment by RemieRichards** [comment]
@Tokiko1 < -- That's a "ping" Just @ and the user's name.

**Pull request merged**
