### PR TITLE
Port of baystation's crew manifest

### PR DESCRIPTION
**Pull request by ghost**
Viewable as a ghost and also in the lobby screen.

Ignore the revert things, I'm a bad git newbie and committed something I did earlier to master.

### CODE REVIEW

**Comment by Atskadan** [comment]
ooooooooooooooooooooooooooooooooooooooooooooooooooooo

**Comment by RemieRichards** [comment]
Bay always know how to use Associative lists well. I positively Squee whenever I see Listname[variablename] from them.

:+1:

**Comment by Iamgoofball** [comment]
Yesssssssssssss

**Comment by ghost** [comment]
I can't think of anything else to add to this so go ahead and merge it.

**Pull request merged**
