### PR TITLE
Gun cabinets in the armory!

### PR DESCRIPTION
**Pull request by JStheguy**
Uses Nienhaus' gun cabinet sprites in place of the racks in the armory.
ss13gruelvendor

### CODE REVIEW

**Comment by Atskadan** [comment]
This isn't really the best way to do it. You should make the gun cabinets a new item and place them in the armory instead of just editing the vars.

**Comment by Atskadan** [comment]
@JStheguy

**Comment by Iamgoofball** [comment]
he can't update this PR anymore because he nuked the repo

 JStheguy wants to merge 1 commit into NTStation:master from unknown repository

**Comment by ghost** [comment]
Weird. I might redo this and make them a child of crates or something.

**Comment by Atskadan** [comment]
not a good way to do it, and the branch was nuked for whatever reason.
if you want to redo it, make it an actual item and place them on the map

**Pull request closed without merging**
