### PR TITLE
Increases chances of chemical-induced hydroponics mutations

### PR DESCRIPTION
**Pull request by ghost**
I was playing botanist for the first time in a very long while recently and finally had a chance to try the most efficient way to get species mutations, which is dripping plants with 5 units of mutagen. Unfortunately species mutations are so unlikely I had to apply an estimated 240 units of mutagen 5 units at a time before I got one. That's around 48 tries. It's a 1 in 10 chance, so you'd think it would be more common than that, but in practice it's not.

Getting and using ~240 units of mutagen took a very long time, mostly due to the chemist's lab being unpowered and abandoned until I realised the equipment was unpowered and hacked the APC to fix it. That doesn't happen every round, but it's not uncommon to take longer than five minutes to get mutagen due to an unresponsive or missing chemist or a lack of energy in the chem dispenser. And 5 - 10 minutes can be a quarter of a round when the server is busy. So making the supply the player does get more effective seems fair to me.

Species mutations can occur at harvesting time, but it's even rarer than chemical-induced ones. I thought it would be a good idea to increase the likelihood of chemical-induced hydroponics mutations, to make the weapons and other useful plants you can grow in hydroponics practical to pursue. Depending on the round type, it's much easier to either steal a weapon or spawn a traitor item, meaning you very rarely see deathnettles and deathberries because they're a lot of work for little or no reward. It's a shame because they're interesting and unique ways to dispatch of someone that require effort to have available.

The proposed values:

Plant dies: 1/10 --> 1/17
Species mutates: 1/10 --> 1/5
Hard mutation: 1/7 --> 1/11
Soft mutation: 1/4 --> 1/7
Nothing: 1/5 --> 1/8
Weeds mutate: 1/10 --> 1/5
Pests mutate: 1/10 --> 1/5
Nothing 2: 0

### CODE REVIEW

**Comment by Tokiko1** [comment]
You should probably raise the species/weed/pest chance even higher by reducing soft/hard mutations chances at 5u. Like, double or even triple their current chances. The chances are way, waaay too low. 

Whenever I want to do botany traitoring, I don't even sign up as botanist, I go doctor/chemist instead because the amount of mutagen it takes makes it completely impractical.

**Comment by ghost** [comment]
I'm glad you agree, I was worried this would be shot down. I'll look at doing that, thanks.

**Comment by ACCount12** [comment]
:+1:

**Comment by ghost** [comment]
I changed them. These are the old values compared to the current ones:

Plant dies: 1/10 --> 1/17
Species mutates: 1/10 --> 1/5
Hard mutation: 1/7 --> 1/11
Soft mutation: 1/4 --> 1/7
Nothing: 1/5 --> 1/8
Weeds mutate: 1/10 --> 1/5
Pests mutate: 1/10 --> 1/5
Nothing 2: 1/100 --> 0

I did some trials on random.org to see how much mutagen and how many attempts it took to get a species mutation with both sets of probabilities, but I realised random.org isn't comparable to BYOND's random number generator. So I'm going to try it in-game.

**Comment by Iamgoofball** [comment]
i love you

**Comment by Tokiko1** [comment]
Merge when?

**Pull request merged**
