### PR TITLE
[don't merge just yet]You can now climb on tables and racks.

### PR DESCRIPTION
**Pull request by Iamgoofball**
seriously why was this not done before

hulks can't climb on tables or racks, they just smash them instead because hulk smash or whatever

### CODE REVIEW

**Comment by Atskadan** [comment]
this is really bad
tables and racks are used as pseudowalls all over the place on the map
climbing on them will lead to all sorts of problems
>climb into HoP office
>climb into kitchen/bar
>climb into medbay/chemistry
>climb into arrivals checkpoint
etc etc

**Comment by Iamgoofball** [comment]
if an area is secure enough this is a problem

it should of had windoors on the tile w/ the table to start with

**Comment by Iamgoofball** [comment]
If tables were climable at the start this wouldn't be an issue.

If you give me a list of areas I can beef up table security and add windoors.

**Comment by Atskadan** [comment]
what benefits are there in climbing over tables?
do you really think adding windoors to everything is a solution to a problem that shouldnt even exist?

**Comment by RemieRichards** [comment]
Don't like it :-1: My reasons are the same as the others.

**Pull request closed without merging**
