### PR TITLE
Gar mesons and satchel revert

### PR DESCRIPTION
**Pull request by ghost**
Reverted the name of the satchel to 'industrial' satchel. it was engineering before because i was going to add a mining/atmos satchel, but i dropped that and so I'll keep them back to as they were before.

Added GAR MESONS! which will be available in the equipment locker once this PR is merged:

https://github.com/NTStation/NTstation13/pull/665

### CODE REVIEW

**Comment by Iamgoofball** [comment]
um

can we have the standard sprite mesons available in the locker alongside these

i'd like to mine and not look like uguu animes please

**Comment by ghost** [comment]
um

can you pay attention and actually read pr code

**Comment by Iamgoofball** [comment]
oh

why the fuck did we name the vending machine "mining equipment locker"

that's such a shit name and it makes you think it's in the actual lockers the miners spawn near.

**Comment by Atskadan** [comment]
its actually the "mining equipment vendor"

**Comment by ghost** [comment]
Bug ergo about it, it's named equipment_locker.dm

**Pull request closed without merging**
