### PR TITLE
Adds various detective tweaks.

### PR DESCRIPTION
**Pull request by MrSnapwalk**
Adds a new grey detective uniform. Sprites by myself.
Adds a detective's flask, and a standard flask for mapmakers. Sprites from Bay.
Removes the tie from the brown detective trenchcoat, and adds it to the hard-worn suit.
Makes the leather satchel the default detective satchel, and makes lace-up shoes the default detective footwear.
Makes the detective spawn with sunglasses.
Makes the Forensic Scanner weight class 2 (instead of weight class 3), allowing it to fit into a pocket.
Removes the the virtually unused evidence bags from the detective's spawning gear (a box of them are still in his office, however).

### CODE REVIEW

**Comment by MrSnapwalk** [comment]
Agh, merge conflicts. Gotta fix these real quick.

**Comment by MrSnapwalk** [comment]
I've been told that these merge conflicts aren't actually real, and are due to settings being wrong somewhere. I've updated my suit.dmi and suits.dmi files to be consistent with #755, so it may or may not be ready to merge. Please let me know!

**Comment by Atskadan** [comment]
:-1: to moving the tie to the worn suit

**Comment by MrSnapwalk** [comment]
Could I ask why?

**Comment by ghost** [comment]
I changed the lockers and shit around as well as some other shit so make sure you're on a fresh, completely updated branch. Pull from master to find the conflicting files.

**Comment by Atskadan** [comment]
i think the worn suit looks good on its own as a plain shirt with pants and adding a tie to it would make it look less simplistic
its not like most detectives wont be wearing the coat anyway

**Comment by MrSnapwalk** [comment]
If you intend to wear the coat with anything else, however, it looks like utter crap due to the tie. Besides, all the rest of the suits have built-in ties (blue suit, black suit, etc).

**Comment by Atskadan** [comment]
make the tie an accessory

**Comment by Atskadan** [comment]
is that somehow not a good idea because it sounds like a pretty good idea to me

**Comment by MrSnapwalk** [comment]
Eh, fuck it. Time for a clean PR!

**Pull request closed without merging**
