### PR TITLE
[WIP][DON'TMERGE]Makeshift Armor

### PR DESCRIPTION
**Pull request by Iamgoofball**
Awhile back we discussed Makeshift Armors for the crew when those damned nuke ops trample their lawn and kill shit.

http://www.ss13.eu/phpbb/viewtopic.php?f=5&t=2117

The poll for this ended in a yes, but it was never done because everyone's gottagofastcumonstepitup

But, since the speed nerf is gonna be reapplied soon, plus these suits slowing you down, you may be buff and tough with this metal suit, but you'll be slow as fuck, and easy to hit with stun batons and tasers and such.

This is a WIP because of two things:
1. I don't have sprites.
2. I need to come up with a construction method.

Don't merge this yet because it's not finished and the code doesn't compile because no sprites.

I'll rerun the poll if needed.

### CODE REVIEW

**Comment by ghost** [comment]
I've made makeshift armour for someone but it was never added.
http://i.imgur.com/DPTSMr1.png
http://puu.sh/5Ssju.dmi

**Comment by Iamgoofball** [comment]
Looks nice, could be implemented.

**Comment by Atskadan** [comment]
> But, since the speed nerf is gonna be reapplied soon

no?

**Comment by Iamgoofball** [comment]
http://i.imgur.com/abSsWh6.png?1
Looks like new speed is gonna win.

**Comment by Atskadan** [comment]
4 votes
and speed needs an in game poll, not just a forum one

**Comment by Iamgoofball** [comment]
still is winning

if it doesn't win, no big deal, I'll just tinker with armor code till I can set a custom slowdown value to ensure no sanic metal men running around

**Comment by ghost** [comment]
Where is that poll located?

**Comment by Atskadan** [comment]
forums

**Comment by Iamgoofball** [comment]
i still think we should wait on ingame polls until we have a better system for them, but alrighty, I'll track down erro for the poll unless someone else is hosting it now

this way we can get a headstart on the poll instead of only remembering to put it up 2 years from now

**Comment by optimumtact** [comment]
@Iamgoofball might I suggest, if you guys have it you use razharas table crafting stuff?
e:for the construction that is

**Comment by Atskadan** [comment]
Of course we have it, @optimumtact. It predates NT's existence, I'm fairly sure.

**Comment by Iamgoofball** [comment]
ye, I was gonna do that

I'm working on some other more important projects then this right now, I'll get back to this soon.

**Pull request closed without merging**
