### PR TITLE
AYY LMAO

### PR DESCRIPTION
**Pull request by Atskadan**
ayyyyyyyyyyyyyy lmao

### CODE REVIEW

**Comment by ColonicAcid** [comment]
ayyyyy lmao

**Comment by RemieRichards** [comment]
You're all mad.

**Comment by ColonicAcid** [comment]
ayyyyyyyy'm stupid

**Comment by ghost** [comment]
this should be a thing xenomorphs say

**Comment by ColonicAcid** [comment]
everyone should say it
literally everyone

**Comment by Tokiko1** [comment]
Add more stupid phrasings to this if you're already at it.

**Comment by ghost** [comment]
'i play jim otis!!!'

**Comment by ColonicAcid** [comment]
"who play jim otis?"

**Comment by RemieRichards** [comment]
Pointless but whatever.

**Pull request merged**
