### PR TITLE
Reduces all stuns by 20%

### PR DESCRIPTION
**Pull request by ghost**
10 ---> 8
5 ---> 4

Stun baton remains a unique 7 stunforce, sitting in between flashes and tasers.

Also span'd a bunch of common messages that should have spans. Every message should have spans. Spans are love.

Poll and discussion here: http://tgstation13.org/phpBB/viewtopic.php?f=14&t=830

### CODE REVIEW

**Comment by ghost** [comment]
control f for flashbangs on the files m8

**Comment by Kraseo** [comment]
why

**Comment by Iamgoofball** [comment]
:-1:

**Comment by Neerti** [comment]
You could explain why you disagree goof

**Comment by Iamgoofball** [comment]
we already got the HG stun nerf stuff, right?

**Comment by ghost** [comment]
Nope, that was all reverted. Move speed and stun times were reverted to pre-HG. For reference, HG's stun nerf was 50% almost across the board, with some exceptions.

**Comment by ike709** [comment]
:-1: :-1: :-1:

**Comment by ghost** [comment]
Cool thumbs that mean literally nothing.

**Comment by ACCount12** [comment]
:-1:

**Comment by ghost** [comment]
The thumbs have defeated me

Will revise more extensively, thanks for the actual input though.

**Pull request closed without merging**
