### PR TITLE
[PORT] [WIP] Ports Rapid Prototyping from BS12. [dont merge yet]

### PR DESCRIPTION
**Pull request by Iamgoofball**
wpn3ksd
Credit goes to @Zuhayr for the code.
Credit goes to @MrSnapwalk for sprites.
I just got it to a position in which it works enough that it can be used, sort of.

There still might be parts that don't work, which I'm still trying to find. If you find any, let me know.

This PR adds Rapid Prototyping, a system to produce your own unique gadgets and gizmos in science, so you have something to do other then "spend 5 minutes grinding R&D levels then SSDing".

Right now you can build all components at roundstart, but the items are really shit w/o research for better stock parts. You can upgrade the components using stock parts from R&D.

All devices are made of Chassis, Primers, Triggers, and Power Supplies.

For example, I could have a Helmet Chassis with a Prototype Bluespace Crystal, an Impact Trigger, a Micro Battery, and a Field Projector.

I charge the device in a Recharger like the ones security uses to charge their tasers, and then I put the helmet on. It now works like an Reactive Teleport Armor, because the Impact Trigger activates the field projector, which will then activate the BS crystal, teleporting me away due to it being on my chest.

I could also make a Taser like the one we use in the station with the following:
Large Device Chassis
Microbattery
Energy Projector
Manual Trigger
Stunner

Or an Egun, just swapping the stunner for a Lens.

Or, I could make a Cryotube Gun with:
Small Device Chassis
Energy Projector
Cell Mount w/ any type of cell
Manual Trigger
Genetic Scrambler
Concussive Deharmonizer
Medical Boost Module

The Medical Boost Module is key here, as it reverses the effects of the previous two modules, making them heal instead of do damage.

Or I could make an AI controlled Flasher, just like the wall mounted ones, except portable.
Machine Frame(not in yet, gonna be in soon though, need sprites)
Field Projector
Cell Mount w/ best battery you can get + best capacitor you can get to ensure it has enough charge to not need recharges constantly.
Flasher
Synthetic Trigger

All the AI has to do is click on the device, and it'll flash everyone in the area who is not wearing sunglasses.

The possibilities of Rapid Prototyping are near endless.

NOTE: The reason that setup.dm stuff is there is because it refuses to see the flags unless it was in there. No clue why, but it did.

### CODE REVIEW

**Comment by ghost** [comment]
this is so cool

**Comment by GunHog** [comment]
WANT.

**Comment by RemieRichards** [comment]
I'll trust the code because it's @Zuhayr 's code. but TEST IT THOROUGHLY

**Comment by MistakeNot4892** [comment]
What the cock, no, do not merge. This is maybe a quarter finished and since this code was pulled I've totally rewritten it.

Bad bad bad idea. If you do merge it, don't blame me for it breaking or being horrible.

EDIT: Unless it's a -total- rewrite of what I had on my repo in which case go your hardest.

**Comment by Iamgoofball** [comment]
Thats why I slapped all the work in progress shit on it.

If this gets mergd with the code as is I will have to murder some people.

**Comment by RemieRichards** [comment]
Don't worry @Iamgoofball @Zuhayr this won't get merged any time soon.
So a re-port of Zu's new code can be done, or a rewrite, if you really want to.

**Comment by Iamgoofball** [comment]
You know what, I'm just gonna close this for now and get back to it a bit later.

**Comment by GunHog** [comment]
B-BUT MUH AI CONTROLLED FLASHER TURRETS!
MY RETARDATION GUN!
MY TORTURE ARMOR THAT HEALS AND STUNS YOU UPON BEING HIT!

**Pull request closed without merging**
