### PR TITLE
Ports LOOC

### PR DESCRIPTION
**Pull request by ghost**
Credit to bay.

Dunno why we don't have this yet.

((Doing this)) is byond retarded.

### CODE REVIEW

**Comment by ghost** [comment]
Also might have missed something, don't merge this yet.

**Comment by ghost** [comment]
I tried this on /tg/station, but people didn't like it. :+1: 

Paranoia about IC in OOC in LOOC I think? I can't really remember, that doesn't make sense though. LOOC by its nature can only be heard by those who can hear you IC.

> ((Doing this)) is byond retarded.

**Comment by ike709** [comment]
What have you done... You monster.

**Comment by Atskadan** [comment]
should have a thread so admins can be aware and make policy shit blahblah also vote yeah

**Comment by Iamgoofball** [comment]
Disable ghosts using it.

Bay12 can trust their players not to abuse it.
We can't.

**Comment by ghost** [comment]
rip

**Pull request closed without merging**
