### PR TITLE
Fixing assistant registration, take three.

### LINKED ISSUE #802: Assistant registration broken!
https://github.com/NTStation/NTstation13/pull/411

This was broken by niggles' /tg/ merge.

But I am working on a fix.

And I still love miggles for doing the /tg/ merge.

### PR DESCRIPTION
**Pull request by ghost**
Fixes https://github.com/NTStation/NTstation13/issues/802

Scanning an assistant's ID card with your own will give them an alt title depending on your job now in addition to basic access. An example would be a medical doctor scanning an ID card and the assistant having the job title of 'nurse' with medbay access.

I'm not especially creative so if people have suggestions they can leave them below.

### CODE REVIEW

**Comment by JStheguy** [comment]
SHITTY ASSISTANT NAME IDEAS AHOY (As possible replacements for the ones already in the PR):
Scientist's Assistant: Lab Assistant
Head of Staff's Assistant: (Whatever Head Position)'s Intern
QM's Assistant: Quartermaster's Accountant (Gotta Keep Dem Expenditures In Line)
Cargo Tech's Assistant: Crate Mover
Chemist's Assistant: Junior Chemist
Geneticist's Assistant: Junior Geneticist
Virologist's Assistant: Junior Virologist
Roboticist's Assistant: Junior Roboticist

**Comment by MrSnapwalk** [comment]
Instead of "Junior _____" for those last ones, why not stuff like this?
Chemist's Assistant: Pharmacist
Geneticist's Assistant: Test Subject
Roboticist's Assistant: Mechatronic Technician

Couldn't think of anything for the Virologist.

**Comment by GunHog** [comment]
> Couldn't think of anything for the Virologist.

Disease carrier

**Comment by Atskadan** [comment]
Captain's Squire (capt)
Secretary (hop)
Research Supervisor (rd)
Head Nurse (cmo)
Emergency Technician (ce)
Deputy (hos)
Waiter (bartender, chef)
Gardener (botanist)
Lab Assistant (scientist)
Robotic Technician (roboticist)
Pharmaceutical Technician (chemist)
Nurse (doctor)
Test Subject (geneticist, virologist)
Mover (ct)
Ore Hauler (miner)
Accountant (qm)
Electrician (engineer)
Welder (atmos)
Recruit (officer)
Private Investigator (det)
Prison Guard (warden)
Journalist (librarian) 
Disciple (chaplain)
Paralegal (lawyer)
Assistant Assistant (assistant) (alt: sub-human)
Comedian (clown)
Silent Actor (mime)
Custodian (janitor)

**Comment by ike709** [comment]
> Accountant (qm)

Implying money is ever a thing.

**Comment by Atskadan** [comment]
implying cargo points arent currency

**Comment by GunHog** [comment]
@ike709 You never know...we could have it one day...

**Comment by ghost** [comment]
Accountant will be perfect for the HoP's sissy once he is Head Jew of the station's currency.

**Comment by Atskadan** [comment]
currency doesnt exist tho

**Comment by ghost** [comment]
Changed Det's assistant to PI so the detective can have a personal snitch
Changed mime and clown assistant names to be more unique
Shortened qm's assistant title

This is primarily a bugfix and people can submit their changes to the titles later after it's merged, I'm personally happy with what I have and if people want to make changes to the titles later that's fine with me.

**Comment by Atskadan** [comment]
fucking "sprout" what the fuck paprika denied worst PR ever hitler/10

**Comment by ghost** [comment]
it's cute fuck u

**Comment by Atskadan** [comment]
ill fuckin sprout YOU kid

**Pull request merged**
