### PR TITLE
Cleans up the Ancient Power Armour files

### PR DESCRIPTION
**Pull request by RemieRichards**
Old code modernised for today's standards, was turned down by /tg/ because no one wanted the files, even if they're cleaner now.

Adds sprites to them (Credit Nienhaus)

### CODE REVIEW

**Comment by Atskadan** [comment]
Cool!
Plan to work on these soon?

**Comment by RemieRichards** [comment]
Maybe, Only bothered PR'ing it because I had the code around. They function (The fully spawnable suits and the parts) However you can't build them, even by "attaching" the pieces to the main suit.

I originally cleaned up the files to modern standards because back then there was quite a bit of talk about Reviving them, so I assisted by modernising the base code.

Being NTStation and rules on content being essentially non-existent (as long as people want it) I don't see why I can't get them constructable and in game proper.

**Comment by Atskadan** [comment]
I'm sure that would be fine. Could work well with Gun Hog's proposed armor additions.

**Comment by StarToad** [comment]
I was thinking of making modular power armor as a fun RnD researchable sometime in the future. This'll be a nice base.

**Pull request merged**
