### PR TITLE
SWAT helmet sprites changed. Syndicate SWAT helmet added.

### PR DESCRIPTION
**Pull request by ACCount12**
Totally not a copy of https://github.com/tgstation/-tg-station/pull/4361

### CODE REVIEW

**Comment by ghost** [comment]
thumps up good add bro

**Comment by ghost** [comment]
You're welcome :us:

**Comment by ghost** [comment]
not you faggot

**Comment by ghost** [comment]
> Copy of tgstation/-tg-station#4361

:us:

**Comment by ACCount12** [comment]
fixed

**Pull request merged**
