### PR TITLE
New emotes

### PR DESCRIPTION
**Pull request by Atskadan**
Thumbsup, thumbsdown, smirk, and pout.
Suggest more!

### CODE REVIEW

**Comment by GunHog** [comment]
Let the AI beep and boop as the cyborgs do!

**Comment by Atskadan** [comment]
travis is dumb :palm_tree:

**Comment by ghost** [comment]
Think you can hide stuff from me!
http://puu.sh/8Vkq5.png

**Comment by Atskadan** [comment]
what stuff

**Comment by ghost** [comment]
http://puu.sh/8Vkq5.png

**Comment by ghost** [comment]
Goddamnit Miggles.
http://puu.sh/8Vkq5.png

**Comment by Atskadan** [comment]
what

**Comment by Iamgoofball** [comment]
GODDAMNIT MIGGLES.
http://puu.sh/8Vkq5.png

**Comment by Atskadan** [comment]
yeah and

**Comment by Atskadan** [comment]
there's no issues, so it doesnt matter

**Pull request merged**
