### PR TITLE
adds a fuck ton of new hair ported from vg

### PR DESCRIPTION
**Pull request by ghost**
adds 29 new hair styles
22 ported from vg, by Kokuten.
1 by myself
the last 6 by MrSnapwalk

### CODE REVIEW

**Comment by Tokiko1** [comment]
Oh this sounds nice. Can you show a screenshot with the new hairs?

**Comment by ghost** [comment]
Sprites were done by Kokuten

**Comment by Bilgecrank** [comment]
http://i.imgur.com/tHVUx0R.png

http://i.imgur.com/UHBRezI.png

Here are the sheets, should you like to look more closely.

**Comment by Tokiko1** [comment]
Those look really nice!

**Comment by RemieRichards** [comment]
Thanks for these @Kokuten 

Do you mind if we port some of your other sprites too? Mechs etc.

**Comment by Bilgecrank** [comment]
Well, technically, nothing is stopping you considering the fact that they're all posted so openly on the /vg/station forums. Though, I suppose if you credit me for the work, there's nothing wrong with you using them. It'd be nice to see them enjoyed in other places.

**Comment by RemieRichards** [comment]
@Kokuten Thanks, I always find it's best to ask first.

**Pull request merged**
