### PR TITLE
Modify glock

### PR DESCRIPTION
**Pull request by golfer45**
Allows the glock to be modified to shoot .45. Using a surgical drill on a empty glock will start the modification. Using it on a glock with ammo should result in being shot. After modification the glock will only accept .45 mags.

### CODE REVIEW

**Comment by Atskadan** [comment]
It needs to have a drawback, like the revolver.

**Comment by ghost** [comment]
I like it, but it needs to have a chance to explode like an IED so we can make glocknade jokes.

This is basically a free unlocked 1911 for science so I'm really against it not having some kind of downside.

**Comment by Dorsisdwarf** [comment]
Make it so that after one clip it has a 75% chance of exploding when fired.

**Comment by golfer45** [comment]
How about a chance of a jam. That needs to be cleared by reloading?

**Comment by Atskadan** [comment]
or have it blow up in your face like the revolver does

**Comment by golfer45** [comment]
I dont like the idea of it blowing up, that will make it kinda useless. I'd rather something like a jam that forces the user to clear it. That way it's less effective than the 1911.

**Comment by golfer45** [comment]
About what swagile said, I could do something like the crit chance during modification, however blowing up woudn't make sense without any rounds inside. It would probably be more along the line of "You slip forcing the drill into your head!".

**Comment by Atskadan** [comment]
If there's rounds inside when you drill it, it blows up with a 100% chance
The detective's revolver is modifiable to shoot .357 but because that's OP it gives it a big chance to blow up in your hand, destroying it.
Glocks are good enough for what they are that you shouldn't be able to basically turn them into 1911's with very little penalty. Jamming the gun just means a few clicks to get it firing again and most of the time you won't be firing constantly anyway.

**Comment by golfer45** [comment]
I disagree, A glock only does 20 brute(both the 9mm and .45 varient) meaning 5 hits are needed for a successful crit. The only advantage gained from changing to .45 is a increase in force meaning each round will knock the target down. However the magazine size also falls from 10 to 8. Regardless unless someone surprises someone I expect it to take a full 8 rounds to crit someone, leaving 3 rounds for missing. A chance high enough to cause at least 1 jam per mag would slow down the shooter enough to give the target a chance to escape or disarm the attacker. The revolver on the other hand does 60 brute damage and causes knockdown with a 7(6?) round cylinder. Making the modified revolver a vastly superior weapon. Except of course for the chance of explosion. To give the modified glock a chance of explosion similar to that of the revolver it would have to be on par with it. However the revolver is vastly superior.

**Comment by golfer45** [comment]
Regarding the 100% chance of explosion from drilling a loaded glock. It's not a bad idea but it's not enough either. Any player smart enough to know not to drill a loaded weapon, then has no disadvantage to modification.

**Comment by Tokiko1** [comment]
Knockdown is pretty powerful. Also nothing stops you from pulling out an unmodified gun and emptying that in poor person who has just been knocked down from your first shot.

I like the idea of jamming easily but it should take quite some time to fix. Maybe have some internal parts of the gun mess up and force you to stand still and repair it with a tool before being able to use it again?

**Comment by Atskadan** [comment]
There is honestly already a problem with people making glocks when they shouldn't. You shouldn't be trying to justify your changes with "but it takes 5 hits to crit" because weapons as semi-easily available as the glock do not <i>ever</i> need a buff. Modifying a glock to shoot stun rounds, like Tokiko said, would easily let you use another weapon to finish the target, basically turning it into a free, shittier stun revolver.
There are plenty of ghetto weapons already that have their place, we do not need more powerful ones.

**Comment by Atskadan** [comment]
no, swagile
just no
to everything you said

**Comment by ghost** [comment]
To be fair in order to even get .45 mags you need to use a protolathe anyway

**Comment by Iamgoofball** [comment]
where was the poll voting this "no"

**Pull request closed without merging**
