### PR TITLE
[Port] Mineral Storage Access

### PR DESCRIPTION
**Pull request by ghost**
Relabeled Mineral Storeroom access to Mineral Storage since the storeroom doesn't exist any more.

Mineral Storage gives you access to the ore redemption machine, instead of keeping a list of req_one_access for various jobs. The intention is to make it easier to manage accesses and make it easier to tell who could use the machine.

Miners and their superiors now have access to the machine. If this becomes an issue I can adjust it.

Moved the mineral redemption machine to the delivery office.

screenshot 2014-04-12 16 03 14

Ported from TGS.

### CODE REVIEW

**Comment by ghost** [comment]
@metacide

**Comment by Atskadan** [comment]
:+1:

**Comment by Atskadan** [comment]
We can't automatically merge this pull request.

**Comment by ghost** [comment]
Updated. All yours.

**Comment by Metacide** [comment]
That's very handy, thanks. I'll merge it into my main branch of MetaStation with the next update on /tg/'s side too. :+1:

**Pull request merged**
