### PR TITLE
Cortical borers [Testing Phase]

### PR DESCRIPTION
**Pull request by RemieRichards**
All of baystation12's Borer features

Control of all Carbon mobs
different/more chemicals for borers
Sprites for all Directions (Why didn't bay do this?)
Reworked the hide verb to be handle_hide() so larva and borers get it without copy pasta

(Who committed FILE_DIRs? Good job I removed em!)

Thread/Poll = http://www.ss13.eu/phpbb/viewtopic.php?f=42&t=3861&p=118207#p118207

(This is a new pr? No it isn't you saw NOTHING!)

### CODE REVIEW

**Comment by ghost** [comment]
:+1:

**Comment by GunHog** [comment]
So I have begun playing with this because FUN...
It is difficult to test this alone, though.
- I recommend giving the chemical and borer health meters as part of the Borer's HUD, just as lings, blobs, and xenos do. 
- There are not that many interesting chemicals to secrete! Please add some more "fun" ones, such as Mindbreaker!
- You cannot secrete anything while directly controlling the host. This makes me sad!
- What does "Torment Host" do?
- It seems possible to infest aliens, and potentially other things, but they cannot actually take control. Secrete does not seem to work either.

I would like to test how borging and other things work while controlling a host, but as I lack friends, testing something like that is not fun.

A runtime occurs when trying to humanize a host monkey, or vise versa (via admin commands):
runtime error: Cannot read null.uni_identity
proc name: humanize (/mob/living/carbon/proc/humanize)
  source file: transform_procs.dm,132
  usr: the monkey (283) (/mob/living/carbon/monkey)
  src: the monkey (283) (/mob/living/carbon/monkey)
  call stack:
the monkey (283) (/mob/living/carbon/monkey): humanize(67, null)
/datum/admins (/datum/admins): Topic("_src_=holder;humanone=[mob_31...", /list (/list))
Gun Hog (/client): Topic("_src_=holder;humanone=[mob_31...", /list (/list), /datum/admins (/datum/admins))

**Comment by RemieRichards** [comment]
@GunHog I've tested myself, and CONTROLLING Aliens is possible, but only the ones that are of /carbon, the ones you would see controlled by a player naturally, if that still does not work then I must have changed something along the way.

You can't secrete chemicals into the host when you are incharge because you ARE the host mob.
I understand the appeal of secrete free hyperzine but that's a little imbalanced.

Torment Host is a fluff verb, I just haven't removed it from the Bay file I ported.

More chemicals, ok sure.

HUD objects, K sure.

and I'll look into the runtime.

**Comment by Atskadan** [comment]
Torment Host seems a little redundant - maybe make it turn the screen BLOODY RED SO REAL like you are when you have lower health, even if you're at full health? Even though that doesn't do anything, it makes it a little more fun.

**Comment by RemieRichards** [comment]
I just had a thought based on your idea miggles, what if it had it's own unique image? like a quick flash of like the inside of a pixely brain? that sounds cool as fuck.

**Comment by Iamgoofball** [comment]
That could be interesting.

**Comment by Atskadan** [comment]
That would be cool, ye

**Comment by Atskadan** [comment]
Progress?

**Comment by RemieRichards** [comment]
Sorry, I haven't been able to dedicate much time to this PR, I'll close it and come back with the suggested changes.

**Comment by Atskadan** [comment]
I don't see a point in closing it if you're just going to take a break.

**Comment by RemieRichards** [comment]
Cleaner PR, Less Commits etc.

**Comment by Atskadan** [comment]
Fair enough.

**Pull request closed without merging**
