### PR TITLE
Meson and further mining changes

### PR DESCRIPTION
**Pull request by ghost**
- MESONS REVERTED TO OLD MESONS
- MESONS REMOVED FROM ENGIEVENDORS TO MAKE THEM A BIT MORE SCARCE
- ADVANCED MESONS **REMOVED**
- NORMAL MESONS HAVE A HIGHER MINERAL/RESEARCH COST
- LOWCHANCE (EAST ASTEROID) HAS SLIGHTLY MORE MINERALS NOW
- NORMAL CHANCE ASTEROID TURF MINERAL RATE REELED BACK A BIT (IT WAS A BIT _TOO_ MINERAL-RICH EVERY TIME I ITESTED)
- MESONS NO LONGER HAVE PSEUDO NIGHT VISION (USE A FLASHLIGHT WITH THEM)
- GAR GLASSES ADDED TO MINING EQUIPMENT LOCKER, WHY THE FUCK DID MINERS NOT EVER HAVE GAR GLASSES, DO YOU EVEN DRILL

### CODE REVIEW

**Comment by ghost** [comment]
https://www.youtube.com/watch?v=l3ierL5ZOG0

**Comment by Atskadan** [comment]
why not give miners advanced mesons at the start and engineers normal mesons

**Comment by GunHog** [comment]
Not sure if like....

**Comment by ghost** [comment]
Because normal mesons allow you to use ghetto thermal vision by tracking people with light sources behind walls. This has the advantage of seeing all structures/terrain in the station regardless of light sources, but also removes the pseudo-night vision and pseudo-thermal features that mesons used to have which were icky. I'm going to throw up a poll on this.

**Comment by ghost** [comment]
http://tgstation13.org/phpBB/viewtopic.php?f=14&t=587

Gonna leave this up to the poll here. I prefer mesons being a single item personally, but I can easily revert it if seperate items are a thing people like more. Miners are DEFINITELY getting advanced mesons are roundstart though, because fuckkkkk mining in the dark.

**Comment by cultist-chan** [comment]
Nevermind redacted, confused NTstation with TGstation.

**Comment by GunHog** [comment]
That Avatar is the cutest CC I have seen yet!

**Comment by cultist-chan** [comment]
Thanks gunhog... haha

**Comment by ghost** [comment]
It's my fault for commenting on the /tg/ thread with my NT pr anyway. But that's how we've 'fixed' mining here, and it seems to work. Mining droprates are a biiiit too much on NT atm but this PR fixes that by reeling them in.

**Comment by ghost** [comment]
Holy fuck what a good idea. I'll see what I can do.

**Comment by ghost** [comment]
travis build failed because other PR isn't merged, merge that first before this.

**Comment by ghost** [comment]
I'm going to add all my new shit to this thing/a single new pr instead because seperate prs are literally, literally hitler and i'll probably overwrite something so h-here i go

**Comment by ghost** [comment]
added the gar mesons to this pr so you can merge this shit up

**Pull request merged**
