### PR TITLE
Pepperspray is now not shit.

### PR DESCRIPTION
**Pull request by ghost**
- If you don't have mouth or eye covering, it weakens (knockdown) as much as a flash does.
- If you only have eye covering, it doesn't weaken, but you'll still take the temp damage shit.
- If you only have mouth covering, it'll stun 20% less.

This affects teargas grenades by extension. Enjoy throwing them and mass-burning everyone's eyeballs out.

### CODE REVIEW

**Comment by ghost** [comment]
ss 2014-07-07 at 12 14 09

Considering nerfing the range to 3 tiles instead of 4 on the spray, but god damn teargas grenades are actually good and it's amazing.

**Comment by ike709** [comment]
Paprka BUFFING something instead of nerfing the shit out of it? What? I didn't know you had it in you! 10/10 I might use teargas grenades now.

**Comment by ghost** [comment]
I've only really nerfed shit me or other NT contributors have implemented because they've usually been a little OP like the tommy gun and shit.

I also buffed harm baton damage!

**Comment by ACCount12** [comment]
Weaken when mouth is uncovered must be 3-5, not 8. 
:+1: anyway.

**Comment by ghost** [comment]
Nah, the 8 is for when you MOUTH is covered but not your eyes. So in other words, someone spraying pepperspray into just your eyes is slightly better than someone spraying pepperspray into your eyes AND mouth.

Eye protection should be the real kicker here because it's what ultimately protects you. If you get hit in just the mouth by pepperspray the effect is marginal.

**Comment by Dorsisdwarf** [comment]
Oh my god all of the yes. Pepper sprays are the least used sec item but my absolute favorite. And teargas grenades work properly too?
EDIT: Apparently they do. This is a good good thing.

**Comment by Tokiko1** [comment]
Add the screaming emote when hit by it back in maybe?

**Comment by Tokiko1** [comment]
Actually...what happens if you fill a spraybottle with this and polyacid? Do you get an inescapeable deathspray?

**Comment by ghost** [comment]
mite b cool

**Comment by ghost** [comment]
I'm probably going to do something on /tg/ but scaled down since stuns on /tg/ are scaled down once the feature freeze is over.

**Pull request closed without merging**
