### PR TITLE
Breath mask and internals box bug fix + new satchels/backpacks [DO NOT MERGE/WIP]

### LINKED ISSUE #591: RD doesn't spawn with an internals box
The last 3-4 times I have chosen the RD i have ot spawned with an internals box, this doesn't happen with any other job.

### PR DESCRIPTION
**Pull request by ghost**
Fixes https://github.com/NTStation/NTstation13/issues/591

Adds a toggle option for the breath mask, but instead of it being up on your head, it hangs down around your neck. Re-worded the code for pushing masks up to allow for other things to be pushed out of the way (cigarettes up behind your ear, for example) in directions that aren't just up.

### CODE REVIEW

**Comment by ghost** [comment]
I'm gonna leave this one as WIP for a bit because I want to add robotics and mining-specific satchels/backpacks.

**Comment by RemieRichards** [comment]
is it good to go now you've got Robo+Mining in?

**Comment by ghost** [comment]
Since I want this merged ASAP for possible updatings I'm gonna leave the mining satchel/backpack out of this PR because I do not have the sprites for it yet.

**Comment by ghost** [comment]
Done, merge that shit up.

**Comment by ghost** [comment]
@dannno fixed!

**Comment by RemieRichards** [comment]
@paprka no it isn't, "You pushing"

**Comment by ghost** [comment]
> :T

**Comment by RemieRichards** [comment]
> but is very 

but it is very
or 
but it's very :P

**Comment by ghost** [comment]
THAT'S NOT MY MISTAKE IT'S DANNNOS' I'M PRETTY SURE

**Pull request merged**
