### PR TITLE
[DO NOT MERGE] Added a Barney the dinosaur suit to the autodrobe. 

### PR DESCRIPTION
**Pull request by Intigracy**
http://www.ss13.eu/phpbb/viewtopic.php?f=48&t=4389&sid=6ce3fe739e3bbaa5c0cf58f01894b61c

Because I'm sick and twisted in the head and want everyone else to hate Barney as much as I did as a child.

https://www.youtube.com/watch?v=GjbR9rHI9Vw

https://www.youtube.com/watch?v=Vzo0iHrivVQ

### CODE REVIEW

**Comment by ghost** [comment]
:-1:  Sprite looks to much like coderart for me to like it.

**Comment by Petethegoat** [comment]
not sure if want

**Comment by KazeEspada** [comment]
NO! PLEASE GOD NO!

Although, the code is good.

**Comment by ghost** [comment]
:-1:

**Comment by Zelacks** [comment]
yes please! YES PLEASE!

**Comment by Intigracy** [comment]
So much for no veto/copyright rules.

**Comment by Atskadan** [comment]
but neither of those rules are there in the rules

**Pull request closed without merging**
