### PR TITLE
Adds Undershirts [Merge dis]

### PR DESCRIPTION
**Pull request by RemieRichards**
Sprites by MrSnapwalk mainly

They are in the Preview
They are on your Random'd characters
They are in Game
They are in your save files
They are changeable via clicking on a Dresser
They make you sexy, too sexy for your shirt, so sexy it hurts.

(Yes I know I said I'd port the bay ones but they're really really different to how we do things, so coded from scratch)

Also removed the FILE_DIRs, Again.

### CODE REVIEW

**Comment by Petethegoat** [comment]
Tested save file functionality?

**Comment by RemieRichards** [comment]
I admit, I have not, But it's functionally identical to things that do work (No excuse I know, it's just it's 00:16 here and I've got 6th form tomorrow)

**Comment by Petethegoat** [comment]
Fair enough. Whoever wants to merge, please check that first.

**Comment by MrSnapwalk** [comment]
Merge this SANIC FAST please. Been waiting quite a while for this.

**Comment by Iamgoofball** [comment]
there should be a big button at the bottom
that lets you merge

**Comment by ghost** [comment]
This can't be automatically merged.

**Comment by RemieRichards** [comment]
Merged from Master, Merge dis shit.

**Pull request merged**
