### PR TITLE
Adds sprite from baystation for PunPun.

### PR DESCRIPTION
**Pull request by Intigracy**
Puts new monkey/punpun on the map in place of var edited punpun. If you do just an edit of the monkey's sprite, if he catches fire or you put something on him he reverts to monkey1 as his icon state.

### CODE REVIEW

**Comment by Iamgoofball** [comment]
:+1: x :100:

**Comment by ghost** [comment]
cute

**Comment by GunHog** [comment]
:+1:

**Comment by ghost** [comment]
:+1:

**Comment by Atskadan** [comment]
:+1:

**Pull request merged**
