### PR TITLE
Makes the Singularity work like Interior Decorator Nar'sie to reduce some of the lag.

### PR DESCRIPTION
**Pull request by Iamgoofball**
lt8q8pm

### CODE REVIEW

**Comment by Niknakflak** [comment]
Ewww  0/10 thumbs down.

**Comment by Iamgoofball** [comment]
I'm working on better sprites for it now

**Comment by GunHog** [comment]
I would wait to see how well the new beta reduces lag before we nerf the singulo.

**Comment by Atskadan** [comment]
what

**Comment by GunHog** [comment]
This: http://www.byond.com/forum/?post=1549601#comment9795251

That update has the potential to de-lag the singularity, removing the need to turn it into...well...that....

**Comment by RemieRichards** [comment]
As of current, that looks icky.

I side with GunHog here, we really should trial the new Byond beta with it's Object referencing optimisation. (However /vg/ have apparently reported it did jack shit to their lag.)

**Comment by Iamgoofball** [comment]
VG's got different nar'sie and singularity code then us as they are bay based.

Also I didn't even know that byond beta existed.

**Comment by RemieRichards** [comment]
Big fucking woop, Not what I was talking about Goof. They've tested the Byond Beta, and it did jack shit to their lag, But we should still do our own tests.

**Comment by Iamgoofball** [comment]
Sorry.

**Comment by wild-billy** [comment]
The new byond update improves the performance of new(), not del().
It won't really affect singulo lag, which is mainly due to mass del() and shit code.

**Comment by theOperand** [comment]
this looks like shit and it removes fun from the singularity.
:-1:

**Comment by Iamgoofball** [comment]
i lost the sprites I had for this to make it look better so rip

**Pull request closed without merging**
