### PR TITLE
A new away mission

### PR DESCRIPTION
**Pull request by ghost**
I like to call it 'syndicates try to make a cool space station and study plasma like NT and fail horribly'

Clean up the mess they made and steal their loot. Not meant to be taken very seriously, many robust syndie and wild animal mobs + asteroid monsters in this one. Plus incredibly robust loot from said syndies. Preferably used on an event day or something, it'll most likely lag normal rounds up. I'd love to see a robust crew tackle the gauntlet!

adasd

### CODE REVIEW

**Comment by WJohn** [comment]
Dude come on the whole "loads of monsters + insane loot + lack of detail" trio is why away missions are awful.

**Comment by Iamgoofball** [comment]
yes, that

it's why we killed away missions in the first place

**Comment by ghost** [comment]
Several of the away missions have pretty decent detail though. Also goofball's clown planet is like the worst offender of that trio.

Running away missions for weeks at a time instead of turning them off after a few days is why they suck ass, because they get old and predictable.

**Comment by WJohn** [comment]
> decently detailed

no don't even lie to yourself about that, their detail is incomparable to that of the station. And yes, while it is true that running the exact same away mission for weeks at a time murders its replayability, that's not really our fault. That's SoSs' decision with the configs, although understandably not a good one. Away missions are going to need some serious redesigning first because their execution is horrible.

**Comment by ghost** [comment]
It's always been a gimmick and not a very seriously thought out gameplay mechanic and i don't think anyone's arguing against that but this is literally just me breaking in dream maker again so i can get situated for actual station map making and bugfixes i didn't know it would piss people off that much.

Also I'm assuming the lack of detail in most of the away missions was intentional which is why I didn't spend a ton of time making this full of shit, wouldn't that make the server lag to hell and back?

**Comment by Iamgoofball** [comment]
we should really just move away missions to the empty z-level and allow you to telescience there

**Comment by ghost** [comment]
Wouldn't that break the loot if you could just telesci snatch it all up?

**Comment by Iamgoofball** [comment]
we could do what goon did and only allow you to telescience into certain tiles on that z-level, so we can have specified telescience entry points to telesci areas.

**Comment by ghost** [comment]
sounds more fun than gateway, honestly!

**Pull request closed without merging**
