### PR TITLE
[DON'T MERGE] VGstation Ports

### PR DESCRIPTION
**Pull request by Iamgoofball**
Adds a Metal Detector to Security, for making sure people aren't smuggling in weapons.

Adds the Mini Meteor toy to the Arcade Machine.

Adds the Inacusiate chemical and recipe. Inacusiate is a chemical that will instantly help any deafness you might have from explosions.

### CODE REVIEW

**Comment by Atskadan** [comment]
descriptions

**Comment by Iamgoofball** [comment]
Once I finish porting sure

**Comment by Atskadan** [comment]
:-1: to the metal detector. If you're ballsy enough to jump into the brig and kill officers in their natural habitat, you should be rewarded for it. Also, just carrying a gun or a melee weapon will magically set it off, but other bits of metal don't? That's not a metal detector, that's a meta detector.
The code itself also doesn't use complete paths for some reason.

**Comment by Iamgoofball** [comment]
alright, then, I'll find something else to port to replace it.

**Comment by ghost** [comment]
Well I like the idea of a metal detector but nobody enters brig unless they're about to shoot the place up or just a grey tide shitter trespassing, nobody legitimately enters sec to visit permabrig and stuff. I think for aesthetics, it'd be cool, watching nuke ops set it off one by one as they storm the station, but other than that it doesn't have much actual use.

How complex is the code? If it's rather simple I don't see a problem with it being in front of the permabrig for visitors and aesthetics, but not the normal brig.

**Comment by Atskadan** [comment]
cant merge

**Comment by Atskadan** [comment]
because it is outdated and has conflicts

**Pull request closed without merging**
