### PR TITLE
SSU Update

### PR DESCRIPTION
**Pull request by ghost**
Mostly to sync with my TGS PR
-SSUs will no longer eject its contents if it runs out of power unless it's already open
-Unpowered SSUs can be crowbarred open if they are not locked
-Some other changes from Giacom's feedback

### CODE REVIEW

**Comment by Atskadan** [comment]
will wait for further changes suggested by gia

**Comment by Atskadan** [comment]
@Ikarrus

**Comment by ghost** [comment]
It's not ready yet

**Comment by ghost** [comment]
Unfortunately, there are some conflicts that I do not have the time to resolve yet. His changes were mostly optimizations anyhow.

**Comment by ghost** [comment]
Probably not applicable anymore now that you guys merged with TG

**Pull request closed without merging**
