### PR TITLE
[WIP] The -Lathe Update

### PR DESCRIPTION
**Pull request by ghost**
Here's the idea in a nutshell:
- Nerf the fuck out of the autolathe, make it public access somewhere
- Autolathe will retain its simple list menu but only produce simple items from now on
- Add 'Heavy Lathe' utilizing old unused sprites:
  clip 2014-05-18 at 11 08 26
- Heavy Lathe will have a queuing system, categories, and will be able to produce complex devices **IN ADDITION** to the normal autolathe items. Essentially, the old autolathe with all the nifty unique complex stuff that was gutted from the autolathe.
- Protolathe will adapt the same queuing system the heavy lathe has for the benefit of science as well in this update.

All are welcome to add suggestions and comments in the thread below, please keep this to code comments and stuff.

http://tgstation13.org/phpBB/viewtopic.php?f=14&t=464

### CODE REVIEW

**Comment by Atskadan** [comment]
neat

**Comment by RemieRichards** [comment]
Let me guess, you're going to "Borrow" this queuing system from the Robotics Fabricator code, Right? I don't care where the code comes from to be honest Just make sure it's clean and Proc'd if it's a large amount of copy pasta

**Comment by Iamgoofball** [comment]
make heavy lathe public access too

otherwise that completely kills part of the gang weapon update

**Comment by ghost** [comment]
What? Why? The current autolathe isn't public access and never has been.

**Comment by Iamgoofball** [comment]
Er, sorry, I should of phrased that better

Don't make the heavy lathe as fortified as the AI core, or need the mission impossible theme playing in the background to break into.

**Comment by ghost** [comment]
it's just going to replace the normal lathe hopefully if i ever finish this

**Comment by Iamgoofball** [comment]
cool beans

**Comment by ghost** [comment]
Closed for now. Any futher updates that warrant reopening will happen in a future PR or branch. ANYONE is welcome to pick this up if you have free time and a decent understanding of the UI system for the queuing and stuff, no credit needed. Discussion until then will happen below:
http://tgstation13.org/phpBB/viewtopic.php?f=14&t=464

Sankyuu.

**Pull request closed without merging**
