### PR TITLE
Readds large crossbow to the protolathe

### PR DESCRIPTION
**Pull request by ghost**
I didn't want this code to go unused, so this readds the large crossbow to the protolathe with:

-New sprites
-New descriptions
-New prices

And it is fairly simple to distinguish the two, so I do not believe there will be "HOLY SHIT TRAITOR LYNCHMOB GO" if someone happens to build one of these with recovered syndie tech.

### CODE REVIEW

**Comment by ChangelingRain** [comment]
flat-out double the cost, it's a 5-hit crit and stun through armor, as it's the largebow

**Comment by ghost** [comment]
This should be better to bring it in line with the mini crossbow.

**Comment by drynwyn** [comment]
Note that this can be built without recovering any syndie tech if someone deconstructs a pair of energy relays.

**Comment by Atskadan** [comment]
Yeah, the illegal requirement should be higher.

**Comment by ghost** [comment]
I wasn't aware of the energy relay thing, I'll bump it to 5. :aries:

**Comment by drynwyn** [comment]
I would say just 4. At 5 it requires 2 traitor items deconstructed to produce.

**Comment by ghost** [comment]
you can decon a parapen or a mini ebow to get 5 unless the wiki is outdated, which is the intended reverse engineering process here

**Comment by ghost** [comment]
after testing it, parapen gives 4, so here you go.

**Comment by Atskadan** [comment]
it says merge with caution but i dont see any reason for that 
oh now its gone
well this is pretty good, it still needs tator items to be getted

**Pull request merged**
