### PR TITLE
Adds syndicate auto shotguns and improves shotgun ammo

### PR DESCRIPTION
**Pull request by ghost**
- Stun slugs are now named properly.
- Stun shells now contain 5 beanbag pellets, for riot control, available in the protolathe.
- Dragon's breath shell added, it's an incendiary shell that does less damage but has multiple pellets. Available in the protolathe with syndicate research.
- Shotgun shells have comments if you're ever confused as to what the difference is in them. They currently share shell sprites which I'm sure can be replaced in the future if anyone wants to.
- Bulldog shotgun added. It has gone through many iterations and balance changes, but at the moment it is a compact (fits in backpacks, e-gun weight size) 8 round combat shotgun loaded by default with stun slugs, much like the old e-guns used to.
- E-guns removed from the nuke op locker and replaced with shotguns.
- Shotgun magazines added to uplink for various TC prices. Extremely deadly in the right hands, and more deadly than an e-gun, but a lot more clunky to reload and there is no more potentially limitless ammo using station rechargers. Ammo preservation and careful resource planning is key, but the magazines aren't exactly expensive or anything. Looking for feedback on the prices.

Bulldog shotgun and magazine sprites primarily courtesy of ausops. He does it for free.

Edit: Also I fixed the L6 sprites, apparently having an uppercase "L" broke them. Thanks byond!

### CODE REVIEW

**Comment by ghost** [comment]
y-you too travis

**Comment by Lumipharon** [comment]
Ok so I was talking about having incendiary amo avaliable for the smg in irc, and was told it wasn't possible to have the gun have multiple possible different ammotypes, without being a revolver based weapon (like shotguns). But you seem to have added a gun that uses mags and can use different ammo types. How'd you manage this, because I literally said 'why can't we make the smg like pap's proposed shotguns' and got no answers.

**Comment by ghost** [comment]
guncode magic

look at the code and learn, it's extremely simplistic

**Comment by ghost** [comment]
http://tgstation13.org/phpBB/viewtopic.php?f=14&t=677

vote and comment here

**Comment by ghost** [comment]
- Incendiary magazines added for c-20r and protolathe smg, both have 10-round magazines for balancing reasons (yeah less damage, but 20 shots of incendiary with no downside to the regular magazine besides damage seems a little off kilter)
- C-20r incendiary mag is 1tc more than a standard C-20r magazine but deals more damage than 9mm incendiary.
- Hades carbine has description updated to better show what it is
- Protolathe mag requires plasma, 100 per bullet in the magazine, but that's less than an actual sheet anyway (a sheet is 3750 raw plasma, you can make 3 magazines with a single sheet of plasma)

Comment/vote in the thread pls

**Comment by Atskadan** [comment]
idk about giving them incendiary mags for c20r
they already have the shotgun 
oh well its probably ok, just means that op hunters will have to bring fire extinguishers with them too

**Comment by ghost** [comment]
Atmos/CE hardsuit will see some more use I hope.

**Pull request merged**
