### PR TITLE
More posters n shit

### PR DESCRIPTION
**Pull request by JStheguy**
Adds 13 more corporate approved posters and 1 more contraband poster.  (The light-blue on dark blue posters were made by someone else, whose name escapes me at the moment.)
ss13raiders

### CODE REVIEW

**Comment by ghost** [comment]
Are they fixed?

 That's a poster - Error (subtype).
A large piece of space-resistant printed paper. This is a bug, please report the circumstances under which you encountered this poster at https://github.com/NTStation/NTstation13/issues.

ss 2014-06-02 at 05 50 37

The one before 'work for a future' is way too hard to read, also.

**Comment by JStheguy** [comment]
The posters that start out on walls are now removed until I or someone else can both
A. Figure out what is wrong with them.
and
B. Fix that shit.
Hopefully I can do that or at least find a temporary work around.

**Comment by ghost** [comment]
Please fix instead of removing a cool feature of the map that **you** broke.

**Comment by JStheguy** [comment]
Wait, I think I might have fixed the problem right now.
Posters on walls no longer give me an error on my changed code.
A tiny bit more testing and I might be able to readd the maint posters.

**Comment by ghost** [comment]
Well it's just a poster, the map-placed ones have nothing to indicate if they're legit or not, as in they have no subtype on the map.

**Comment by JStheguy** [comment]
The map-placed ones do have a subtype var, but it's set to 0, which is a valid subtype.
Also, scratch the possible unfucking of posters, they actually still are bugged.

**Comment by ghost** [comment]
I guess you could just var-edit the map-placed posters icon_states and serial numbers, but since serial numbers are randomized (?) it wouldn't match up if you took it down and placed it again (which nobody does anyway)

If it really means we can't have pre-placed posters on the map, I don't think that's TOO big of a deal since I really like the addition of legit posters enough for pre-placed posters to be removed (you should add some more rolled-up contraband posters around maint if you're gonna do this I suppose)

**Comment by JStheguy** [comment]
Serial number random generation on the on-wall posters is kinda fucked.
Basically: There is no serial_number by default, which for some reason defaults to the code path of the turf the poster is on, if this occurs the actual correct serial number will be randomly generated.

**Comment by JStheguy** [comment]
Welp, I can't get pre-placed posters to function, so I guess we just add more rolled-up posters around maint and possibly a few legit posters in art storage or something.

**Comment by ghost** [comment]
I added some to sec lockers and the checkpoint, see my PR below this one.

**Comment by JStheguy** [comment]
Ok now I cant into map changes because git wont let me commit map changes.
Fuk it this will have to do.

**Comment by ghost** [comment]
I can put some posters around after this is merged, it's cool.

**Comment by JStheguy** [comment]
Thanks, mate.

**Comment by ghost** [comment]
guh remove the map changes from this one, i'll remove the map posters in a new PR later today

**Comment by JStheguy** [comment]
FUCK I CANT REVERT ANYTHING
EVASIVE ACTION

**Pull request closed without merging**
