### PR TITLE
Winter coats/jackets no longer have thickmaterial flag.

### PR DESCRIPTION
**Pull request by ghost**
This flag is for heavy armor suits and space suits, there is really no reason for winter coats and jackets to have it, it makes them a lot less cosmetic and a lot more powergamey. They're already super robust against the cold as it is.

HoS coat cries at the exclusion from the thickmaterial flag but I'd rather remove it from these coats than give it to the HoS as parapen protection.

### CODE REVIEW

**Comment by Atskadan** [comment]
the hos' other armors already have parapen protection though

**Comment by Atskadan** [comment]
oh thats odd i guess they dont
i swore they did

**Comment by ghost** [comment]
It's literally only winter coats and bomber/leather jackets u_u

/tg/ doesn't have thickmaterial on the HoS jacket or anything so I don't think it's a good idea, but I can easily add it to that and the warden jacket/etc if you want to keep it on the winter coats. I just don't see a reason to.

**Comment by Dorsisdwarf** [comment]
Because this "powergamey" addition is utterly nullified by anyone clever enough to change their target from "chest" to "head" or "Legs"?

**Comment by ghost** [comment]
You can put a syringe through a coat like this ez. Not to mention it just makes healing harder.

**Pull request merged**
