### PR TITLE
[MAP] Secret Document Objectives

### PR DESCRIPTION
**Pull request by ghost**
Adds new steal objective docsgen "Secret Documents"
-A set of secret documents spawn in the vault's filing cabinet, but even syndicate documents qualify as valid steals
-Vault is now motion-alarmed
-Tom moved to Prison

Adds the exchange objective for traitors
-If there are at least 6 traitors, two of them will be selected to make an exchange of secret documents
-There is a low (20%) chance that one of them will have an additional backstab objective, where they will require both sets of documents to win
-Sending syndicate documents to centcom will yield a very large point reward

@metacide

### CODE REVIEW

**Comment by Atskadan** [comment]
:+1: :+1: :+1: 
space rosa

**Comment by Petethegoat** [comment]
This is fucking awesome. You're hero Ikarrus.

**Comment by Spessmen14** [comment]
Spiffy idea! I wonder, would it be possible to make the secret documents a multi-page archive (say, several pages in their own special clipboard/folder) and be copyable by taking photos of the individual pages or placed in the photocopier?

**Comment by smet19** [comment]
@Spessmen14
YOU FUCKEN NECRO

**Comment by Spessmen14** [comment]
Oh go pulse a Syndie bomb.

**Pull request merged**
