### PR TITLE
"Search" button for spawn panel

### PR DESCRIPTION
**Pull request by ACCount12**
Bay-like "Search" button for our (less) laggy spawn panel.

### CODE REVIEW

**Comment by Atskadan** [comment]
explain

**Comment by ACCount12** [comment]
Search button reduces lag amount when you are typing a search query into spawn panel's search field.

**Comment by RemieRichards** [comment]
This is the Debug --> Spawn, Verb isn't it?

**Comment by ACCount12** [comment]
Game Panel -> (Create Object, Quick Create Object, Create Turf, Create Mob) panel

**Comment by RemieRichards** [comment]
Ah, i care less about that one. I only use Debug --> Spawn, because it's largely faster and get's the job done.

**Pull request merged**
