### PR TITLE
Janitor Clothes! (Also other things)

### PR DESCRIPTION
**Pull request by JStheguy**
-Adds an alternate janitor jumpsuit and matching jacket. (http://puu.sh/aeGrO/7cbcf5277a.dmi)
-Adds a magazine for the janitor to read while in his shitty Scruffy cosplay. (NEVERMIND REMOVED)
-Adds varsity jackets in red and blue. (http://i.imgur.com/HZ9KFJf.png)
-Adds NT and Communism undershirts. (http://i.imgur.com/F1h0FrW.png)
Credit to Nien for the janitor stuff.

### CODE REVIEW

**Comment by ghost** [comment]
> no screenshot of undershirts
> no screenshot of varsity jackets

dropped

**Comment by Atskadan** [comment]
yes please screenshots also i dont really approve of adding porno mags to the game
not because it promotes ERP or whatever but just because its stupid

**Comment by ghost** [comment]
There is a screen shot but it was put in the desc.
http://puu.sh/aeFcG/ebc1d04749.png
Edit: You mean of the other stuff that isn't the jani. Ignore me.

**Comment by Atskadan** [comment]
that looks nice
by the way i think we should change all the undershirts to not look torn as fuck because theyre like that for whatever reason and it looks bad

**Comment by JStheguy** [comment]
Yeah
I think whoever did that designed them to fit the shape of rolled down jumpsuits because reasons.

**Pull request merged**
