### PR TITLE
FUCK NINJA

### PR DESCRIPTION
**Pull request by Iamgoofball**
Ninja no longer can be rolled randomly as an event.

This is the single most unbalanced antag in the game. I can kill a wizard ling traitor nuke op cultist that has all the spells, all the cult words, infinite telecrystals, and infinite geome power points easier then I can kill a space ninja with low power.

And someone had the bright idea to make it a random event.

### CODE REVIEW

**Comment by Iamgoofball** [comment]
carn did, according to the comments in the files

**Comment by Niknakflak** [comment]
No No No No No No No No No No
Heavily disagree with this.

**Comment by ghost** [comment]
poll

also improve don't remove :^)))))))))))))))))))))))))))))))))))))

**Comment by GunHog** [comment]
:-1: Agreed with Paprika. Do not remove the best antag position in the game!

**Comment by Dorsisdwarf** [comment]
Fuck random ninja. If you're going to keep ninja as a random event, make Wizard a random event too.

After all, why make some round-dominating overpowered solo antags spawn at random and not others?

**Comment by ghost** [comment]
Because ninja isn't an antag, or it's not supposed to be. It was meant to be the middle ground justice warrior that hunted antags but due to the population being rabid validhunters and lasering ninjas on sight most ninjas just blow anyone that tries to tase them up.

I never quite understood why they got C4.

**Comment by Steelpoint** [comment]
The way the poll and this PR is worded heavily implies its to remove Ninja, and to remove it from the random rotation. (Which makes no logical sense).

If your passionate about something like this, keep the jokes and bad puns out to avoid confusion as you just shooting yourself in the foot.

I don't think this PR should be merged until a properly worded poll is held.

**Comment by Iamgoofball** [comment]
sorry, I should of been way more clear on that poll, my bad

i'll restart it soon, i might just axe the PR as I have a better idea on what to do with ninja

**Comment by Atskadan** [comment]
4 days, ended in no

**Pull request closed without merging**
