### PR TITLE
Thermite Effectiveness Scaling with Volume and Wall Type

### PR DESCRIPTION
**Pull request by ghost**
Poll: http://tgstation13.org/phpBB/viewtopic.php?f=14&t=222

-The more thermite is applied to a wall, the faster it will burn
-Scales between approx 10-25 seconds
-Rwalls require 4x more thermite
-Applying thermite to a wall now leaves a visible stain on the wall
-Igniting thermite makes a sound

### CODE REVIEW

**Comment by Iamgoofball** [comment]
needs a poll, possibly controversial

**Comment by ghost** [comment]
http://tgstation13.org/phpBB/viewtopic.php?f=14&t=222

**Comment by Iamgoofball** [comment]
has the potential to piss people off who are used to 5uing walls

**Comment by Neerti** [comment]
:+1:

**Comment by ghost** [comment]
The poll closed 13-2 In favor.

**Pull request merged**
