### PR TITLE
Poison expansion part 1

### PR DESCRIPTION
**Pull request by Tokiko1**
*Adds chiyanine, a delayed poison that takes 120 cycles(which is around 4 minutes) before it becomes active and starts killing you. Not very useful if your victim is aware of it as it can be easily removed by consuming anti toxin but hiding it in food, drinks or even medicine should leave them clueless as to who poisoned them. Recipe: 1 plasma, 1 radium, 1 aluminium = 3 chiyanine

*Adds mizarudol, a poison that degrades vision. Recipe: 1 plasma, 1 cryptobiolin, results in 3 mizarudol

*Adds maizine, a slow acting, weak poison. Even small amounts remain very long in the body unless you force them out with anti toxins. Recipe: 1 cryptobiolin, 1 chloral, 1 mindbreaker = 3 maizine

*Adds ehuadol, a very dangerous poison. Causes a lot of damage(a third of it is clonedamage!) as well as severe brain and eye damage. Is also metabolized at a slower rate.  Recipe: None! Deathberries only.

*Add jiutin, a weak poison that makes you starve and can be countered by eating. Recipe: 1 radium, 1 lipozine, 1 copper, = 4 jiutin

Some changes to plants:
*Death berries now contain ehuadol in addition to their other chemicals.

*Poison berries now contain maizine in addition to their other chemicals.

### CODE REVIEW

**Comment by ike709** [comment]
I like it. Makes tatorchem more fun than just a chloral syringe gun.

**Comment by ACCount12** [comment]
:+1: for chemical fun

**Comment by ExplosiveCrate** [comment]
:+1:  for actually making death berries deadly

**Comment by Tokiko1** [comment]
This should be working by the way.

**Comment by Lumipharon** [comment]
Neat, nice to have more unique things for tator botanist. Now if only aa botanist could make chiyanine on their own, fucking poison everyone.

**Comment by Tokiko1** [comment]
Any idea which plant should include chiyanine?

**Comment by Lumipharon** [comment]
I would say maybe a new plant, but that would require someone to sprite things. Wouldn't really want to add it to any of the existing plants, since a: the ones that are nasty, already have shit in them, and it wouldn't make sense to have some nasty poison in random 'nice' plants. Except maybe some kind of fungus.

**Pull request merged**
