### PR TITLE
Added a use delay to medical items

### PR DESCRIPTION
**Pull request by ghost**
Poll: http://www.ss13.eu/phpbb/viewtopic.php?f=48&t=4328

Bruise packs and ointments will now have a delay when using it. Applying medical items on yourself will take considerably longer than having someone else apply it on you.

The same goes for repairing augs, borgs, and mechs.

### CODE REVIEW

**Comment by ghost** [comment]
Let me know if this is going to be an issue for you, @Petethegoat 

I was just told you had something planned.

**Comment by ghost** [comment]
Healing people with anything but syringe guns is gonna be a pain. "HOLD STILL!" the doctor shouted as  the greyshirt with 30 burn to the head ran off towards the wizard's last known position.

**Comment by Petethegoat** [comment]
:+1:

**Comment by Neerti** [comment]
Kinda odd to have the thing say 'The Tam Lin has died' instead of just their name without the 'the'.

**Comment by ghost** [comment]
The \The should only appear if if's not a proper noun.

ie "the monkey"

**Comment by Petethegoat** [comment]
In general you can completely omit 'the' or '\the'. I don't think they're ever needed, unless you're doing [src.name] for some reason.

**Comment by Petethegoat** [comment]
Also, I don't think the info class is really appropriate for this? It's mainly used for examine, and I guess I'd use it for static information from things or on things? notice would probably be ideal.

**Comment by ghost** [comment]
I wanted the start of the application to look different than actually applying it.

If it's an issue I can change it.

**Comment by Petethegoat** [comment]
Might warrant adding a new class. I'll think about it.

**Comment by ghost** [comment]
Revised to include augs, borgs, and mechs. Augs take longer to repair than fleshy parts.

**Pull request merged**
