### PR TITLE
[WIP] Socks and stuff

### PR DESCRIPTION
**Pull request by ghost**
Sprites tomorrow

Suggestions now

(Tell me if I missed anything in this code)
(List of socks is at the bottom)

### CODE REVIEW

**Comment by ghost** [comment]
Also should I rename 'none' to 'nude' like undershirts and underwear or call it barefoot?

**Comment by ghost** [comment]
I'll see what travis is pissed about in a second

Edit: just the lack of a socks.dmi pay no mind

**Comment by RemieRichards** [comment]
Knee socks and thigh high socks? Sign me up!
(Code's fine btw, besides your missing icon file)

**Comment by Atskadan** [comment]
>rainbow leggings
i think i have a reason to play clown again

**Comment by WJohn** [comment]
Weee, more style!

**Comment by ghost** [comment]
The only clothing items that include these in their sprite are the sexy clown outfit (green thighhighs I think) and my updated HoS female formal (pantyhose), both of which I will edit and remove once I finish the starting sprites for these.

**Comment by ghost** [comment]
Okay so 
- HoS, Sexy clown, and sundress have had their socks/pantyhose removed
- All new sock sprites
- Some other small changes to the list (white kneehighs for example

**Comment by RemieRichards** [comment]
@paprka merge ready?

**Comment by ghost** [comment]
let me give it a quick test just in case RR

**Comment by RemieRichards** [comment]
Alrighty

**Pull request merged**
